### ISSUE TITLE
Automatically generate & load (module) plugins

### ISSUE THREAD

**Issue by pimlie** [nuxt-community/storybook#1]
Eg if you use `@nuxtjs/fontawesome` icons in your components the plugin generated by that module should also be loaded in storybook

Ideas:
- Support a config structure for modules so they can indicate themselves whether their plugins need to be loaded in storybook or not (but let the user be able to override that)

**Comment by farnabaz** [comment]
This integrator is [loading all nuxt plugins](https://github.com/nuxt-community/storybook/blob/master/storybook/preview.js#L9) in the `main.js`. But there is no possibility for the user to filter or add new plugins.

**Comment by adamskeeled** [comment]
Hey @farnabaz ! That does seem to indeed load the nuxt modules plugins, but doesn't make them available in the Storybook scope. For example, if I have the `@nuxt/vuetify` module and wrap `<v-app>` around my stories, Storybook doesn't recognize that element making everything inside the component break. This currently only works if I add `<v-app>` inside the component itself and that doesn't seem reasonable to have

**Comment by farnabaz** [comment]
> That does seem to indeed load the nuxt modules plugins, but doesn't make them available. 

Actually, nuxt modules are loaded by storybook runtime and are available in the Storybook. But for sure Storybook does not support all of the Nuxt features. 

> For example, if I have the `@nuxt/vuetify` module and wrap `<v-app>` around my stories, Storybook doesn't recognize that element making everything inside the component break. 

`<v-app>` does not provide by `@nuxt/vuetify` and in a nuxt project, you have to put this tag inside your pages or simply in your layouts. Inside the storybook, pages and layouts do not render and these forces to wrap your stories with `<v-app>`.

**Comment by adamskeeled** [comment]
`v-app` doesn't get provided by the nuxt module itself, but it's provided by the Vuetify dependency in it. And it's possible to have vuetify inside the Storybook scope. I already tried it in a simple Storybook app (not using this module) where vuetify would get added inside Storybook via a global decorator where `v-app` then became available to use in stories

**Comment by rlam3** [comment]
Is there a recommended approach on how to get font-awesome and nuxt storybook working together with tailwindcss? I'm looking for an example repo but don't seem to find this anywhere in the documentation.
