### ISSUE TITLE
Can we add custom configuration to addons?

### ISSUE THREAD

**Issue by adamskeeled** [nuxt-community/storybook#100]
I have the addon `@storybook/preset-scss` and I would like to prepend a custom variables file to all SCSS files, and to do so I need to add some custom configurations. However, when I add it I get the message `MODULE NOT FOUND`.
Here is the configuration I'm using (Which I'm already using in another Storybook project but that one isn't currently using @nuxt/storybook):
```javascript
addons: [
    {
      name: '@storybook/preset-scss',
      options: {
        rule: {
          include: [/\.sass$/],
        },
        sassLoaderOptions: {
          prependData: `@import '${customVariablesPath}'`,
          sassOptions: {
            indentedSyntax: true
          }
        },
      }
    },
    {
      name: '@storybook/preset-scss',
      options: {
        rule: {
          include: [/\.scss$/],
        },
        sassLoaderOptions: {
          prependData: `@import '${customVariablesPath}';`,
        },
      }
    },
  ]
```

**Comment by farnabaz** [comment]
Hey,
Thanks for the issue, Currently the module does not support addon configuration. I'll create a PR to add this feature
