### ISSUE TITLE
Uncaught TypeError: ({}) is not a function

### ISSUE THREAD

**Issue by jhswart** [nuxt-community/storybook#101]
### Version
@nuxtjs/storybook: v2.1.0
nuxt: v2.14.3
@nuxt/typescript-runtime: v1.0.0
@nuxt/typescript-build: v2.0.2

### Steps to reproduce
Run storybook through npm: `npm run storybook`
Where `package.json` is setup as:

```
"storybook": "nuxt storybook -s ./static -p 6006"
```

### What is Expected?
Storybook starts and shows stories.

### What is actually happening?
Storybook loads doesn't show stories and in console.log it shows:

<img width="1179" alt="Screenshot 2020-08-21 at 13 36 55" src="https://user-images.githubusercontent.com/20886852/90886803-6583a980-e3b3-11ea-84a9-1b744f2798fd.png">

<img width="364" alt="Screenshot 2020-08-21 at 13 33 51" src="https://user-images.githubusercontent.com/20886852/90886598-fad26e00-e3b2-11ea-9c03-37f714b8168e.png">

(The error occurs in entry.js)

**Comment by farnabaz** [comment]
Could you provide a reproduction project? It works fine for me.
