### ISSUE TITLE
Static files don't load if source directory is repointed

### ISSUE THREAD

**Issue by ryanechternacht** [nuxt-community/storybook#106]
### Version
@nuxtjs/storybook: ^2.1.0
nuxt: ^2.14.0

### Reproduction Link
https://github.com/ryanechternacht/nuxt-storybook-static-issue

### Steps to reproduce
The repo above demonstrates the issue. 

To create it I did the following
1. `npx create-nuxt-app nuxt-storybook-static-issue`
2. `yarn add --dev @nuxtjs/storybook`
3. Added the `TestComponent.vue`, image in `static/img/`, and used it in `pages/index.vue`. Added `TestComponent.stories.js`
4. Checked that everything worked correctly via `yarn nuxt` and `yarn nuxt storybook` (it did).
5. Moved the source directory to `src`. 1) Added `srcDir: 'src'` to `nuxt.config.js`, 2) moved the `assets`, `components`, `layouts`, `middleware`, `pages`, `plugins`, `static`, and `store` directories under a `src` folder
6. reran `yarn nuxt` and `yarn nuxt storybook`. the site is fine, but storybook fails to load the image from the `static` directory. 

### What is Expected?
The image should load in storybook

### What is actually happening?
The image isn't loading in storybook (but works fine on the main site)

**Comment by ryanechternacht** [comment]
By the way, THIS REPO IS AMAZING

I tried doing this like a month ago (and didn't know this repo existed) and EVERYTHING SUCKED. It was clear that nuxt/storybook should be sharing webpack setup, but making them do was painful. THANK YOU SO MUCH FOR DOING THIS

**Comment by farnabaz** [comment]
Hey @ryanechternacht,
Thanks for the issue and your king words :)
The fix will publish in v2.2.0 within two days
