### ISSUE TITLE
How do I integrate storybook with font-awesome icons?

### ISSUE THREAD

**Issue by rlam3** [nuxt-community/storybook#109]
How do I integrate storybook module with font-awesome icons?
Looking for a clear example/demo for this. Thank you!

**Comment by silvio-e** [comment]
@rlam3 what exactly do you need as end result?

I use Fontawesome in my projects like described here: https://github.com/FortAwesome/vue-fontawesome#nuxtjs

With that, the fontawesome component is registered globally and therefore also available in storybook like all the other components.

Does that help?

**Comment by farnabaz** [comment]
You can create a custom story to show font-awesome icons. A simple story could be like this:
```js
import { library } from '@fortawesome/fontawesome-svg-core'

/**
 * Gets icons from library with ["fas", "edit", "fasEdit"] shape
 *
 * @return array
 */
const getLibIcons = (library) => {
  const data = library.definitions

  const toPascalCase = (str) => {
    const camelCase = str.replace(/-([a-z])/g, val => val[1].toUpperCase())
    return camelCase.charAt(0).toUpperCase() + camelCase.slice(1)
  }

  return (Object.keys(data).map(key =>
    Object.keys(data[key]).map(value => [key, value, key + toPascalCase(value)])
  )).reduce((current, next) => current.concat(next), [])
}

export default {
  title: 'Font Awesome Module'
}

export const Icons = () => ({
  data () {
    return {
      icons: getLibIcons(library)
    }
  },
  template: `
    <div>
      <div style="width: 100px; height: 100px; padding: 10px; float: left" class="icons-preview" v-for="icon in icons" :key="icon[1]">
        <div><font-awesome-icon :icon="icon[1]" /></div>
        {{icon[1]}}
      </div>
    </div>
  `
})
```

**Comment by tim-kilian** [comment]
This did not work for me, because the library is empty at the time of reading the story. I needed to make a file, that contained the array of icons.

**Comment by farnabaz** [comment]
@tim-kilian check out https://github.com/nuxt-community/fontawesome-module/pull/20, it should work
