### ISSUE TITLE
Module not found: Error: Can't resolve '@storybook/addon-notes/register'

### ISSUE THREAD

**Issue by allozaur** [nuxt-community/storybook#113]
### Version
@nuxtjs/storybook: v2.1.0
nuxt: v2.14.0

#### 1. Install Nuxt + Storybook module

```bash
yarn create nuxt-app
yarn add --dev @nuxtjs/storybook
yarn add @storybook/preset-scss
yarn add @storybook/addons
yarn add @storybook/addon-knobs
yarn add @storybook/addon-actions
yarn add @storybook/addon-links
yarn add @storybook/theming
```

#### 2. Add `storybook` to `nuxt.config.js`

```js
  storybook: {
    port: 6006,
    stories: [
      '~/**/**/*.stories.js'
    ],
    addons: [
      '@storybook/preset-scss',
      '@storybook/addon-actions/register',
      '@storybook/addon-knobs/register',
      '@storybook/addon-links/register',
      '@storybook/addon-notes/register'
    ]
  },
```

### What is Expected?

I should see empty Storybook in `http://localhost:6006`

### What is actually happening?

![nust-storybook-error](https://user-images.githubusercontent.com/37627284/91640802-77eb8c00-ea20-11ea-85ed-85de86d53f9c.jpg)

**Comment by farnabaz** [comment]
> NOTE: `addon-notes` has been superseded by `addon-docs`, which fixes numerous bugs, supports a richer feature set, and is easier to maintain. [SEE](https://github.com/storybookjs/deprecated-addons/tree/master/addons/notes)  

As the doc says, `@storybook/addon-note` is deprecated and the latest version of notes add on is `5.3.21` which shows that is it not compatible with storybook@6. I do recommend starting to use docs addon.


@shilman, There is a [`6.0.0-alpha.6`](https://www.npmjs.com/package/@storybook/addon-notes/v/6.0.0-alpha.6) beta version for notes addon. Are you have plans to support notes addon in SB6?

**Comment by shilman** [comment]
@farnabaz Probably not. I've requested volunteers to maintain deprecated addons. If there's enough demand, we can release a 6.0 version. But until then 5.x is the latest supported version

**Comment by allozaur** [comment]
Thanks, guys, i solved the problem by using `addon-docs` :) I think that the issue can be closed
