### ISSUE TITLE
Cannot read property 'dark' of undefined

### ISSUE THREAD

**Issue by freezboi** [nuxt-community/storybook#115]
### Version
@nuxtjs/storybook: v2.1.0
nuxt: v2.14.0

### Reproduction Link
https://github.com/freezboi/nuxt-ts-vuetify-storybook-test

### Steps to reproduce
1. Using create-nuxt-app
```
yarn create nuxt-app <project-name>
typescript selected
Vuetify.js selected
```

2. Install Storybook Module + addons
```
yarn add --dev @nuxtjs/storybook
yarn add --dev @storybook/addon-knobs
yarn add --dev @storybook/addon-docs
yarn add --dev @storybook/addon-storysource
```

3. Add nuxt.config.js
```
storybook: {
    addons: [
        '@storybook/addon-knobs/register',
        '@storybook/addon-storysource',
        '@storybook/addon-docs',
    ]
}
```

### What is Expected?
addon docs page should display properly.
When first run, the page is displayed properly, but if you click the Canvas tab and then the Docs tab again, an error occurs.

### What is actually happening?
<img width="1202" alt="error" src="https://user-images.githubusercontent.com/20037780/91659030-f0794800-eb07-11ea-8074-c34b338d62a7.png">

**Comment by farnabaz** [comment]
This is fixed in #124, Please upgrade to the latest version [v2.2.1](https://github.com/nuxt-community/storybook/releases/tag/v2.2.1)
