### ISSUE TITLE
MDX Stories Demo TypeError

### ISSUE THREAD

**Issue by nonlinearcom** [nuxt-community/storybook#116]
The official example on [How to write stories in MDX  format](https://codesandbox.io/s/github/nuxt-community/storybook/tree/master/examples/mdx) seems to be broken?  
I'm getting this error:
`TypeError: undefined is not a function (near '...storyStore.on...')`

**Comment by farnabaz** [comment]
It was a cache issue in codesandbox containers, I've fixed it.
Now, it works as expected :)

Thanks for report
