### ISSUE TITLE
Storybook should not use PORT variable from the .env file if port is specified in the config object

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [nuxt-community/storybook#119]
### Version
@nuxtjs/storybook: 2.2.0
nuxt: v2.14.4

### Reproduction Link
https://codesandbox.io/s/sweet-water-bo2gb?file=/nuxt.config.js

### Steps to reproduce
- create .env file
- add env variable **PORT=3008**
- add **port:4000** property to the storybook config object
- run storybook

### What is Expected?
Port that is specified in the config should be used. I would also not use default PORT property from env at all since it's used for the main application and will usually be busy by it, it would be much better if by default the variable would be something like PORT_STORYBOOK 

### What is actually happening?
port from .env file is used

**Comment by travis5491811** [comment]
Just adding a note that running into this same issue causes me to get the following message on startup `Port 3000 is not available. Would you like to run Storybook on port 3000 instead? (Y/n)` if the main app is **not** running and `Port 3000 is not available. Would you like to run Storybook on port 3001 instead? (Y/n)` if the main app **is** running.

**Comment by pi0** [comment]
Environement variables always have priority over configuration (that's to allow overriding config by devops config without modify source code). You should avoid using `PORT` in `.env` file also for nuxt (and use `nuxt.config` instead with `server.port`)

**Comment by AndrewBogdanovTSS** [comment]
@pi0 but what if I want port to be unique for each environment?

**Comment by farnabaz** [comment]
@AndrewBogdanovTSS If you are using Linux/Mac you can assign port right before the command
```
PORT=4000 yarn nuxt storybook
```
on Windows you may need [cross-env](https://www.npmjs.com/package/cross-env)

**Comment by AndrewBogdanovTSS** [comment]
@farnabaz yes, but that way I will have same problem as with placing it in Nuxt config - there's no way to exclude it from the project and give everyone in the team a safe way to run it on unique port

**Comment by farnabaz** [comment]
@AndrewBogdanovTSS You can assign a unique port for each script in your `package.json`. This solve the port conflict in your development environment

```js
"scripts": {
  "dev": "PORT=3003 nuxt",
  "storybook": "PORT=3004 nuxt storybook"
}
```

**Comment by AndrewBogdanovTSS** [comment]
Maybe we could have alternative port env var something like "PORT_STORYBOOK" which will be used instead of "PORT" if provided?

**Comment by pi0** [comment]
@AndrewBogdanovTSS `PORT` is a standard environment variable for process. You should avoid mixing different envs with single `.env` file and avoid using it inside `.env`. Ahad's solution for providing `PORT` inside scripts, seems the best.

Anyway also supporting `PORT_STORYBOOK` to override should be harmless :)

**Comment by farnabaz** [comment]
@AndrewBogdanovTSS Do you mind to create a PR for it?
