### ISSUE TITLE
Adding global decorators in nuxt config

### ISSUE THREAD

**Issue by adamskeeled** [nuxt-community/storybook#120]
### Is your feature request related to a problem? Please describe.

This is related to a problem I'm having in Vuetify, where, I'm forced to add the `v-app` wrapper around the Vuetify components. In plain Storybook I added a global decorator.

### Describe the solution you'd like

Here in this module I think it would be nice to be able to add a global decorator in the storybook config in `nuxt.config.js`, with the syntax being something like this:
```js
storybook: {
    decorator: '<v-app><story/></v-app>'
},
```
### Describe alternatives you've considered

I think this could work if I did the manual setup and added the global decorator in the `preview.js`, but it didn't seem to work.
If this worked "out-of-the-box" without any manual setup it would be better imo

**Comment by freezboi** [comment]
For manual setup, please refer to the link below.
https://github.com/storybookjs/storybook/issues/4256#issuecomment-677475159
