### ISSUE TITLE
Nuxt Storybook gets stuck in infinite loading cycle when run at localhost:3003

### ISSUE THREAD

**Issue by CSumm** [nuxt-community/storybook#122]
### Version

@nuxtjs/storybook: v2.1.0
Nuxt: v2.14.0

### Reproduction Link
https://github.com/CSumm/portfolio-app

### Steps to reproduce
- Pull current project from repo
- ```yarn install``` all dependencies (Nuxt, Nuxt/Storybook, etc)
- Run ```yarn nuxt storybook```
- Observe the load at localhost:3003

### What is expected
Nuxt Storybook runs and shows current available stories from the components folder at localhost:3003.

### What is actually happening?
Nuxt Storybook remains in an infinite loading loop without errors appearing in the console.

### Screenshot
![Screenshot from 2020-09-04 11-46-31](https://user-images.githubusercontent.com/31711543/92258382-bcee4300-eea4-11ea-9753-8e0fc79007f7.png)
![Screenshot from 2020-09-04 11-52-28](https://user-images.githubusercontent.com/31711543/92259372-2bcb9c00-eea5-11ea-97eb-2a0b4e491f40.png)

**Comment by farnabaz** [comment]
The problem lays in your [`QuantityIncreaseBlock` component](https://github.com/CSumm/portfolio-app/blob/master/components/QuantityIncreaseBlock.vue#L14). Change options to this
```
options: ["lorem","lorem","lorem","lorem","lorem"]
```

**Comment by CSumm** [comment]
Oh, that was the issue thank you! Didn't know that would cause infinite loading to occur. This can be closed out!
