### ISSUE TITLE
Add an option to specify Storybook config directory path

### ISSUE THREAD

**Issue by pocka** [nuxt-community/storybook#131]
### Is your feature request related to a problem? Please describe.

I can't use `.storybook` as a configuration directory, which is a default config directory in Storybook, in `nuxt storybook eject`-ed projects.

### Describe the solution you'd like

Add a CLI flag or a config option (in `nuxt.config.js`) that specifies a Storybook config directory.

### Describe alternatives you've considered

Use `.storybook/` instead of `storybook/` (easy but breaking. I don't think it's worth though)

### Additional context

AFAIK, only Storybook for ReactNative uses `storybook/` as a configuration directory. Using a widely used naming convention reduces users' recognition costs and helps to keep config files clean and simple. e.g. No need to specify a config path in tools such as `@storybook/addon-storyshots`.

**Comment by farnabaz** [comment]
Hey pocka,
Thank you for the issue
Supporting a custom configuration directory will add unnessesary complexity to integration. For now I am not sure whether it worth or not.
