### ISSUE TITLE
Unable to find main.js

### ISSUE THREAD

**Issue by mariomka** [nuxt-community/storybook#142]
### Version
@nuxtjs/storybook: 3.0.0
nuxt: nuxt-edge

### Reproduction Link
Manual setup example.

### Steps to reproduce
```
git clone git@github.com:nuxt-community/storybook.git
cd storybook/examples/manual-setup/
yarn
yarn nuxt-storybook
```

### What is Expected?
Storybook should load the custom main.js.

### What is actually happening?
Storybook throws a warning twice:

```
ℹ Preparing project for development                                                                                       13:16:45
ℹ Initial build may take a while                                                                                          13:16:45
✔ Builder initialized                                                                                                     13:16:45
✔ Nuxt files generated                                                                                                    13:16:45
ℹ Waiting for file changes                                                                                                13:16:45
info @nuxtjs/storybook v3.0.0
info
info => Loading static files from: /Users/mario/Work/storybook/examples/manual-setup/static .
info => Loading presets
WARN Unable to find main.js: /Users/mario/Work/storybook/examples/manual-setup/Users/mario/Work/storybook/examples/manual-setup/.storybook/main
info => Loading presets
WARN Unable to find main.js: /Users/mario/Work/storybook/examples/manual-setup/Users/mario/Work/storybook/examples/manual-setup/.storybook/main
info => Loading config/preview file in "/Users/mario/Work/storybook/examples/manual-setup/.storybook".
info => Loading config/preview file in "/Users/mario/Work/storybook/examples/manual-setup/.storybook".
info => Adding stories defined in "/Users/mario/Work/storybook/examples/manual-setup/.storybook/main.js".
info => Using default Webpack setup.
```

It tries to load the file from the wrong path: `Users/mario/Work/storybook/examples/manual-setup/Users/mario/Work/storybook/examples/manual-setup/.storybook/`

As you can see it duplicate the absolute path.

**Comment by farnabaz** [comment]
This is related to the essential addon. The addon tries to load `main.js` file on register but it does not support absolute configDir. https://github.com/storybookjs/storybook/blob/5aab5b207d0d28bd803d8fcc297cfbabd4825a1b/addons/essentials/src/index.ts#L13

cc @shilman

**Comment by lihbr** [comment]
Just to make sure I got it correctly, basically `3.0.0` is broken because of that?

Tested on multiple projects not sure I found a quick fix to that other than getting back to `2.2.2` 🤔

Is there a way to disable essential addons?

**Comment by mariomka** [comment]
I think the `main.js` file is correctly loaded, at least for the storybook "core". I don't know if it breaks something in essential addon but it seems to works well.

**Comment by lihbr** [comment]
🤔 I've been experiencing from broken stories to blank page with `3.0.0`, will investigate a bit more~

**Comment by leandromatos** [comment]
Has anyone figured out a solution to this error?

**Comment by shilman** [comment]
Sorry missed this the first time. Fix coming later today!

**Comment by leandromatos** [comment]
An open PR to update the dependencies exist #151. 

Can anyone merge and generate a new version of @nuxtjs/storybook please?
