### ISSUE TITLE
nuxt storybook fails when using components with i18n blocks

### ISSUE THREAD

**Issue by snapwich** [nuxt-community/storybook#147]
### Version
@nuxtjs/storybook: 3.0.0
nuxt: 2.14.3

### Reproduction Link
https://codesandbox.io/s/eager-meadow-8eefy?file=/components/test.vue

### Steps to reproduce
Include nuxt-i18n module and use i18n vue SFC block

### What is Expected?
component renders allowing for i18n SFC as documented here: https://kazupon.github.io/vue-i18n/guide/sfc.html#basic-usage

### What is actually happening?
```
ERROR in ./components/test.vue?vue&type=custom&index=0&blockType=i18n (./node_modules/vue-docgen-loader/lib??ref--8!./node_modules/vue-loader/lib??vue-loader-options!./components/test.vue?vue&type=custom&index=0&blockType=i18n) 3:6
Module parse failed: Unexpected token (3:6)
File was processed with these loaders:
 * ./node_modules/vue-docgen-loader/lib/index.js
 * ./node_modules/vue-docgen-loader/lib/index.js
 * ./node_modules/vue-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| 
| {
>   "en": {
|     "test": "test str"
|   }
```

**Comment by farnabaz** [comment]
You need to add `nuxt-i18n` to nuxt modules iside `nuxt.config`. Also as you want to use `SFC` block you need to enable `vue-i18n-loader` module. read [i18n official docs](https://i18n.nuxtjs.org/vue-i18n-loader)


```js
modules: [
    "@nuxt/content",
    [
      "nuxt-i18n",
      {
        vueI18nLoader: true
      }
    ]
  ],
```

I close this issue because it isn't related to storybook. Feel free to ask qny question
