### ISSUE TITLE
Use Nuxt's auto import feature for components

### ISSUE THREAD

**Issue by aaronzdavis** [nuxt-community/storybook#148]
### Is your feature request related to a problem? Please describe.
I would like to use Nuxt's auto import feature for my components in Storybook. Currently, Storybook is requiring me to import components using the standard Vue import method, but this is frustrating when my components are following the Nuxt auto import component setup.

### Describe the solution you'd like
Setup Storybook to leverage Nuxt's auto import feature.

### Describe alternatives you've considered
Reverting back to importing components as we would in Vue.

**Comment by farnabaz** [comment]
The current version of Storybook supports auto import. Take a look at examples
 https://github.com/nuxt-community/storybook/tree/master/examples/manual-setup

**Comment by aaronzdavis** [comment]
Thanks for the quick response @farnabaz. You're right. I updated my nuxt and nuxt/storybook packages and the auto import works now as expected.
