### ISSUE TITLE
Support for i18n in stories

### ISSUE THREAD

**Issue by tim-kilian** [nuxt-community/storybook#149]
### Is your feature request related to a problem? Please describe.

I want to use `$t` in my stroy components and a global to switch the languages.

### Describe the solution you'd like

A documentation on either https://storybook.nuxtjs.org or https://i18n.nuxtjs.org

### Describe alternatives you've considered

Support it out of the box.

### Additional context

Currently storybook is throwing `$t is not a function` when I try to use the `$t` function in the related components.

**Comment by farnabaz** [comment]
Do you use the latest version of Storybook? `nuxt-i18n` works fine with the latest version

**Comment by tim-kilian** [comment]
I had an error in my config and fixed my issue, but i still would like to have support for a language switcher control build in.

**Comment by tim-kilian** [comment]
More Context: it does not work out of the box with a custom configuration in `.storybook`. [manual setup](https://storybook.nuxtjs.org/manual-setup/)

**Comment by farnabaz** [comment]
@tim-kilian I can't reproduce the issue. Could you provide a reproduction sample?

**Comment by tim-kilian** [comment]
I tried to set up a codesandbox with nuxt storybook, but could not make it running, do you have a template for me?

**Comment by xinbenlv** [comment]
I have the same problem.

I will try to setup a minimized app and upload to github, you can check out and run `yarn nuxt storybook` and you shall see the error when trying to change language by clicking on the spanish

https://github.com/xinbenlv-just-learning/storybook-nuxt-mini-bug-app

Screenshot:

**Comment by tim-kilian** [comment]
This is my example. My language switcher works in stories, but not in the docs section. I think this is because the `prepareForInline` function differs from the `prepare` function. Also it seems that `prepareForInline` do not load i18n correctly, because I that $i18n is undefined in the compontents vue instance.

https://github.com/tim-kilian/nuxt-storybook-i18n-example

![image](https://user-images.githubusercontent.com/5788010/100120930-d0dc8c00-2e78-11eb-91d7-2842cfd67558.png)

Also there is a warning that says `storyFn` is deprecated. Maybe there is a better way to add a global language picker then my way?

```
\`storyFn\` is deprecated and will be removed in Storybook 7.0.

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-storyfn
```

**Comment by farnabaz** [comment]
> My language switcher works in stories, but not in the docs section

@tim-kilian It should be fixed in https://github.com/nuxt-community/storybook/commit/0488263c407ee99e54ef3bc742cfebfa2763435b and will publish this week 🙂

**Comment by farnabaz** [comment]
@tim-kilian [v3.3.0](https://github.com/nuxt-community/storybook/releases/tag/v3.3.0) is out. Can you confirm the fix?

**Comment by tim-kilian** [comment]
Yes, I got it fixed now. Thanks for the help. Look at https://github.com/tim-kilian/nuxt-storybook-i18n-example for my solution.

**Comment by alexcroox** [comment]
@tim-kilian can you confirm you have to eject add i18n support? I assume the @nuxtjs/storybook config hook api is of no use here?
