### ISSUE TITLE
Manual Setup Breaks Docs Addon

### ISSUE THREAD

**Issue by dankellett** [nuxt-community/storybook#168]
This is similar to the following issue, but not the same
https://github.com/nuxt-community/storybook/issues/115

### Version
@nuxtjs/storybook: 3.1.0
nuxt: 2.14.6

### Reproduction Link
https://github.com/dankellett/nuxt-storybook-docs-broken

### Steps to reproduce
1. Using create-nuxt-app
```
yarn create nuxt-app <project-name>
typescript selected
Vuetify.js selected
```

2. Install Storybook Module + addons
```
yarn add --dev @nuxtjs/storybook
yarn add --dev @storybook/addon-knobs
yarn add --dev @storybook/addon-docs
yarn add --dev @storybook/addon-storysource
```
3. Create .storybook config files main.js and preview.js using template from nuxt.js documentation
```
yarn nuxt storybook eject
```
4. Run storybook
```
yarn run storybook
```
### What is Expected?
addon docs page should display properly.
When first run, the page is displayed properly, but if you click the Canvas tab and then the Docs tab again, an error occurs.

### What is actually happening?
![image](https://user-images.githubusercontent.com/1899114/98597511-0173d180-228e-11eb-9a37-dc512c7b408f.png)

**Comment by farnabaz** [comment]
@dankellett Thank you for the issue.
In your `.storybook/preview.js` change first line to 
```js
export * from '~~/.nuxt-storybook/storybook/preview.js'
```

It should fix the issue.

**Comment by dankellett** [comment]
@farnabaz perfect. Thank you.
