### ISSUE TITLE
Best way to deploy the storybook along with the nuxt site?

### ISSUE THREAD

**Issue by Martin7mind** [nuxt-community/storybook#173]
Hi!

We're deploying our nuxt site with docker in kubernetes. If we add this module, whats the best way of deploying it? maybe just building the storybook and making it available at mydomain.com/components from the statics folder?

**Comment by farnabaz** [comment]
I recommend building the storybook publishing as the static folder as you mentioned.   
If you don't want to publish it static, consider creating a separate pod for the storybook.
