### ISSUE TITLE
Allow Vue dev tools in production 

### ISSUE THREAD

**Issue by drewbaker** [nuxt-community/storybook#176]
Hey guys, is it possible to config this to allow Vue tools inspector when build and deployed to production?

**Comment by fbtwitter** [comment]
Anyway how to run vue dev tools in dev mode instead of auto activating the react dev tools environment in storybook dev

**Comment by drewbaker** [comment]
Figured out the way to do this is actually a Netlify "feature". You must do this as your Netlify build command: `    CI= npm storybook-build` (it's the `CI=` part that does the magic).
