### ISSUE TITLE
Component render twice without plugin

### ISSUE THREAD

**Issue by gaetansenn** [nuxt-community/storybook#190]
### Version
@nuxtjs/storybook: v3.2.0
nuxt-edge: "latest"

### Reproduction Link
You can reproduce the bug here https://github.com/gaetansenn/dw-ui/tree/plugin-injection

### Steps to reproduce
`cd storybook; yarn serve` storybook will start
check your console to see the problem

![Screenshot 2020-12-01 at 11 17 00](https://user-images.githubusercontent.com/2774075/100727596-c06f6880-33c6-11eb-8594-f23bd74fe7c2.png)
![Screenshot 2020-12-01 at 11 16 52](https://user-images.githubusercontent.com/2774075/100727598-c107ff00-33c6-11eb-9403-00bb95c81ff8.png)

I also tried to extend the webpackFinal from https://storybook.nuxtjs.org/manual-setup#create-mainjs documentation but I got the error.

```js
webpackFinal (config, options) {
    config = options.nuxtStorybookConfig.webpackFinal(config, options)

    if (process.env.NODE_ENV == 'development') config.resolve.alias['@dewib/dw-ui'] = path.resolve(__dirname, '../../lib')

    return config
  },
```

![Screenshot 2020-12-01 at 11 24 27](https://user-images.githubusercontent.com/2774075/100728534-f6f9b300-33c7-11eb-8207-56fb2b96584e.png)

### What is Expected?
Should inject `$dewib` plugin

### What is actually happening?
`$dewib` is not injected the second time from Canvas tab and never from Docs tab. 
Is that normal that the component is rendered twice ?

**Comment by farnabaz** [comment]
I don't have an idea right now about repeated calls of config but for the Docs tab, change your `preview.js` to 

```js
export * from '~~/.nuxt-storybook/storybook/preview.js'
```

**Comment by gaetansenn** [comment]
@farnabaz you just solved my render problem. Now my component is rendered inside the Docs section. Tks you 😄 

Why `export * from '~~/.nuxt-storybook/storybook/preview.js'` ?
Still have my double instance with the plugin not injected the first time.
What about the `config = options.nuxtStorybookConfig.webpackFinal(config, options)` error ?

**Comment by farnabaz** [comment]
@gaetansenn After your issue, I just found that the docs were not updated. I just pushed the fix for docs. And docs are [UPDATED](https://storybook.nuxtjs.org/manual-setup/#create-mainjs)
As you are using v3.2 you should change the `main.js` to this
```js
const { nuxifyStorybook } = require('../.nuxt-storybook/storybook/main.js')

module.exports = nuxifyStorybook({
  webpackFinal (config, options) {

    // extend config here
    
    return config
  },
  stories: [
    // Add your stories here
  ],
  addons: [
    // Add your addons here
  ]
})

```

**Comment by gaetansenn** [comment]
@farnabaz That's what I did. Tks again for your help
