### ISSUE TITLE
It seems that the nuxt module is not injected.

### ISSUE THREAD

**Issue by mulder21c** [nuxt-community/storybook#193]
## summary

I'm using `@nuxtjs/dayjs` and `vue-fragment`, and i met the following error:

1. `@nuxtjs/dayjs` module error in `Molecules/ContentCard/Vod Type`,`Molecules/ContentCard/Live Type` and `Template/Main Page`
    
     In case of `Molecules/ContentCard/Vod Type` and `Molecules/ContentCard/Live Type`,   
     there is no problem when accessing the URL directly, but an error occurs when accessing by activating the `Docs` tab.
      
     ![Molecules-ContentCard-Live-Type-⋅-Storybook](https://user-images.githubusercontent.com/14821565/100842264-eaef1d80-34bb-11eb-9c97-a90c9192655e.png)

     And in case of  `Template/Main Page`, an error occurs even when accessing the URL directly.

     ![Template-Main-Page-Main-Page-⋅-Storybook (2)](https://user-images.githubusercontent.com/14821565/100842194-cd21b880-34bb-11eb-8442-4265ef9db478.png)

2. `vue-fragment` plugin error in `Template/Main Page`
    There is no problem when accessing the URL directly, but an error occurs when accessing by activating the `Docs` tab.
     **[ When activating `Docs` tab ]**
     ![An error occured](https://user-images.githubusercontent.com/14821565/100841082-20930700-34ba-11eb-941c-546f86f66d8f.png)
     [ When accessing the URL directly ]
     ![no problem when accessing the URL directly](https://user-images.githubusercontent.com/14821565/100841206-50daa580-34ba-11eb-8f3f-19a6b69cc3db.png)

How do I fix this?

You can view all codes and test on [my codesandbox](https://codesandbox.io/s/xenodochial-bogdan-lgoiq).

**Comment by farnabaz** [comment]
Fix in [v3.3.0](https://github.com/nuxt-community/storybook/releases/tag/v3.3.0). Feel free to reopen if the issue exists in the new version
