### ISSUE TITLE
Are custom plugins being current loaded? 

### ISSUE THREAD

**Issue by gaabrielcs** [nuxt-community/storybook#197]
I created a plugin inside the Nuxt plugins folder that injects `this.$ga` object where I can access some methods like `this.$ga.event()` and it only loads on the client-side. It is working pretty good in the components I added in my pages but when I try to use it in the stories I always get an error saying the this.$ga is undefined so I am thinking that it is not being loaded by the @nuxt/storybook automatically.

![image](https://user-images.githubusercontent.com/50870887/100921788-c72bd780-34bb-11eb-9af2-10116f7ca639.png)

![image](https://user-images.githubusercontent.com/50870887/100921822-d6128a00-34bb-11eb-8b2b-23bfd7204b2b.png)

**Comment by gaetansenn** [comment]
Should be fixed by this [pull request](https://github.com/nuxt-community/storybook/pull/195)
Have you used the [manual setup](https://storybook.nuxtjs.org/manual-setup) ?

Next time add a reproductible code.

**Comment by farnabaz** [comment]
Fix in [v3.3.0](https://github.com/nuxt-community/storybook/releases/tag/v3.3.0). Feel free to reopen if the issue exists in the new version
