### ISSUE TITLE
Rendering problem

### ISSUE THREAD

**Issue by bmunoz89** [nuxt-community/storybook#201]
I was trying out something very similar to the example with the manual configuration, then I went to the page with the example(https://storybook.nuxtjs.org/examples/manual) to see if I was doing something wrong, and it was there that I noticed that is happening the same problem as well

### Version
@nuxtjs/storybook: 3.3.0
nuxt: 2.14.9

### Reproduction Link
Code: https://codesandbox.io/s/storybook-docs-dont-work-t8s9k
Page: https://t8s9k.sse.codesandbox.io/?path=/docs/link--nuxt-website

### Steps to reproduce
Use @nuxtjs/storybook: 3.2.0 https://codesandbox.io/s/storybook-docs-work-4mvzk

### What is Expected?
To display the nuxt link

### What is actually happening?
The component is not rendered

**Comment by sMesle** [comment]
Still not working on version 3.3.0
