### ISSUE TITLE
Storybook Launch Error When Using Stories From a Module

### ISSUE THREAD

**Issue by ryanrobertsname** [nuxt-community/storybook#208]
### Version
@nuxtjs/storybook: 3.3.0
nuxt: 2.14.12

### Reproduction Link
https://codesandbox.io/s/musing-cerf-so2yx?file=/nuxt.config.js

### Steps to reproduce
1.) In nuxt.config.js / storybook.stories, reference a stories file located in a node_module loaded as a URL dependency.
2.) Run npx nuxt-storybook to launch storybook.

### What is Expected?
Storybook launches without errors.

### What is actually happening?
The following error is thrown when launching:
"(node:983) UnhandledPromiseRejectionWarning: TypeError: Cannot re
ad property 'split' of undefined
    at fromStringWithSourceMap (/sandbox/node_modules/source-list-map/lib/fromStringWithSourceMap.js:15:32)
    at SourceMapSource.listMap (/sandbox/node_modules/webpack-sources/lib/SourceMapSource.js:45:10)
...
...continues
"

### Additional Notes
- When moving the module stories file to ~/ it works fine.
- If using "npm link" to reference a local copy of the module it works fine.
- I also tried loading the stories file via nuxt/storybook API config hook, resulting in the same error.

### Reproduction Screenshot Showing the Error When Launching
<img width="1428" alt="Screen Shot 2020-12-24 at 10 52 41 AM" src="https://user-images.githubusercontent.com/5835411/103103589-d1cb1f80-45d6-11eb-96ed-a4bf2153260f.png">

**Comment by kelfink** [comment]
I've been getting a the same error on a non-nuxt project.  Just Vue with freshly installed storybook.
