### ISSUE TITLE
Tell @nuxt/component to ignore `.stories.js`

### ISSUE THREAD

**Issue by Atinux** [nuxt-community/storybook#23]
When using `components: true`, it includes the `*.stories.js`:

![Screenshot_2020-07-30_at_15 18 59](https://user-images.githubusercontent.com/904724/88931997-cd941380-d27d-11ea-8e82-1bed666aa171.png)

I updated the documentation to add in `.nuxtignore`: https://storybook.nuxtjs.org/setup

I guess it can be improved from a Nuxt POV (see with @pi0 )

**Comment by farnabaz** [comment]
What about adding `**/*.stories.*` in Nuxt ignore?

https://github.com/nuxt/nuxt.js/blob/dev/packages/config/src/config/_common.js#L66-L69

**Comment by pi0** [comment]
nuxt 2 is feature freeze but we can add via compoents module 😊

**Comment by Atinux** [comment]
Agree, a PR to [nuxt/components](https://github.com/nuxt/components) could do the trick :)
