### ISSUE TITLE
Vue components not rendering when @nuxtjs/storybook is used in a Vue Storefront Next project - possibly a Typescript conflict?

### ISSUE THREAD

**Issue by philwolstenholme** [nuxt-community/storybook#233]
Hi,

I am trying to use @nuxtjs/storybook inside a Vue Storefront Next (https://docs.vuestorefront.io/v2/general/key-concepts.html) project.

I can get Storybook to open and to show stories, but the component within the stories are not rendered. For example, if I try and use the example from https://storybook.nuxtjs.org/usage then I see a `<link>` element in devtools, not a rendered `<a>` element:

![Screenshot 2021-02-23 at 11 13 15](https://user-images.githubusercontent.com/6339853/108899122-f6139e80-760f-11eb-96e9-49c1e9f7b593.png)

I then switched to trying to use another simple component:

https://codesandbox.io/s/admiring-pine-2byq7?file=/components/Logo.vue
https://codesandbox.io/s/admiring-pine-2byq7?file=/components/Logo.stories.js

But that doesn't work either, you can see an example of that here: https://pedantic-chandrasekhar-a83cfc.netlify.app/?path=/story/logo--logo (I had trouble getting Storybook to work on Codesandbox).

Vue Storefront Next is based on Nuxt but I had to make a few changes to get Storybook to open:

1) Update the `build` section within `nuxt.config.js`:

```javascript
babel: {
      presets({ envName }) {
        return [
          [
            '@nuxt/babel-preset-app',
            {
              corejs: { version: 3 }
            }
          ]
        ]
      },
      ignore: [/[\/\\]core-js/, /@babel[\/\\]runtime/],
    },
```

2) install `@babel/runtime-corejs3`, `core-js` 3, and `ts-node` 

`ts-node` was necessary because Vue Storefront Next provides a `tsconfig.json` file for development of part of the project, and that makes @nuxtjs/storybook module think the project is a Typescript project (https://github.com/nuxt-community/storybook/blob/e5b3698482873d7129cd763a0422b8c3151cee0b/src/index.ts#L67-L76), but the Vue Storefront project does not use `@nuxt/typescript-runtime` - I am wondering if this is part of the problem?

You can see the package.json content on Codesandbox: https://codesandbox.io/s/admiring-pine-2byq7?file=/package.json

----

Any clues as to how to fix this issue would be SUPER appreciated, thank you! I've spent the best part of a day on this but I don't know enough about Storybook or Nuxt to be able to debug it myself, unfortunately :(

**Comment by philwolstenholme** [comment]
Ah, I've found something interesting.

On a vanilla Nuxt and Nuxt Storybook project `.nuxt-storybook/storybook/preview.js` looks like this:

```javascript
import Vue from 'vue'
import { prepareForInline } from './nuxt-entry';
import '~storybook';

import * as components from '../components';
Object.keys(components).forEach(name => Vue.component(name, components[name]));

const globalParameters = {};
globalParameters.docs = {
    ...globalParameters.docs,
    prepareForInline
}
export const parameters = globalParameters

export const decorators = []
```

But on my Vue Storefront project it looks like this:


```javascript
import Vue from 'vue'
import { prepareForInline } from './nuxt-entry';
import '~storybook';

;

const globalParameters = {};
globalParameters.docs = {
    ...globalParameters.docs,
    prepareForInline
}
export const parameters = globalParameters

export const decorators = []
```

Note the missing lines:

```javascript
import * as components from '../components';
Object.keys(components).forEach(name => Vue.component(name, components[name]));
```

Also, on the Vue Storefront project, `.nuxt-storybook/components/index.js` was missing, whereas it should have contained:

```javascript
export { default as Logo } from '../../components/Logo.vue'
export const LazyLogo = import('../../components/Logo.vue' /* webpackChunkName: "components/logo" */).then(c => c.default || c)
```

It looks like something on the Vue Storefront project is preventing `@nuxtjs/storybook` from properly discovering my components…

**Comment by philwolstenholme** [comment]
Oh wow, turns out I just needed to set `components: true` in `nuxt.config.js` 🤦 

I don't think this is mentioned in the documentation but maybe it should be? I'll make a PR…

**Comment by johncastorina** [comment]
This is not working for me. I am currently working on a component that uses another within it, and the child component is not rendering out to the proper tag.

I set components: true in nuxt config.

**Comment by hmalaud** [comment]
Same as @johncastorina , using Nuxt 3 and a standalone version of storybook, child is not rendered.
