### ISSUE TITLE
Vuex support

### ISSUE THREAD

**Issue by webistomin** [nuxt-community/storybook#236]
Hi! 

Is there a way to use Vuex in this module? Or should I recreate it this way and import directly in my stories everytime?

```js
// .storybook/store.js

import Vue from 'vue'
import Vuex from 'vuex'
Vue.use(Vuex)

import * as mutations from '../store/mutations'
import * as state from '../store/state'
import * as actions from '../store/actions'
import * as getters from '../store/getters'

const store = new Vuex.Store({
 state,
 mutations,
 actions,
 getters,
})

export default store
```

**Comment by webistomin** [comment]
Sorry, I didn't notice the `nuxifyStorybook` function in the documentation.

**Comment by dargmuesli** [comment]
Sorry, but could you please tell me how `nuxifyStorybook` does help here?

**Comment by webistomin** [comment]
> Sorry, but could you please tell me how `nuxifyStorybook` does help here?

`nuxifyStorybook` automatically register your `store` folder inside the `storybook`, so you don't need to import `vuex` directly

**Comment by dargmuesli** [comment]
Ah yes, thank you!
How do you mock the state? I'm currently overwriting the store as to my understanding: https://github.com/maevsi/maevsi/blob/99acd6de4a42c645e8c560265eb8ce837d876c4b/nuxt/components/modal/Modal.stories.js#L13

**Comment by webistomin** [comment]
> overwriting the store

To be honest, I didn't have a task to overwrite the store. Or maybe it's for the best, so the components interact with the store as in the real world.
