### ISSUE TITLE
npx nuxt storybook build fails on a local project

### ISSUE THREAD

**Issue by Atinux** [nuxt-community/storybook#24]
On a local demo, I am trying to run npx nuxt storybook build but I got this error:

![Screenshot 2020-07-30 at 15 58 06](https://user-images.githubusercontent.com/904724/88932178-092edd80-d27e-11ea-82eb-e2147c3a4f2c.png)

**Comment by farnabaz** [comment]
Now we check the first argument and if it isn't a directory we treat arg as a command.  
This fix in https://github.com/nuxt-community/storybook/commit/153f11acf7366158a83ff14a3e78219f2634d03b
