### ISSUE TITLE
--no-manager-cache ?

### ISSUE THREAD

**Issue by cherylcarpenter** [nuxt-community/storybook#244]
Hi,
Having played with this version and the main package of storybook, we are going with your nuxt package! 
One feature I'm missing is the --no-manager-cache flag. I cannot get it to work with 
yarn nuxt storybook --no-manager-cache
Is this a possibility in this version?
Thanks!

**Comment by krisimmig** [comment]
I have the same problem, trying to update the theming of our storybook. Is there another way of invalidating the manager cache in the meantime?
