### ISSUE TITLE
No static folder results in unable to deploy to Netlify - Failed to load static files, no such directory: /opt/build/repo/static

### ISSUE THREAD

**Issue by drewbaker** [nuxt-community/storybook#263]
### Version

@nuxtjs/storybook: 4.0.2
nuxt: 2.15.4

### Steps to reproduce

Try to deploy to Netlify with:

Have no static folder in your repo, then deploy to Netlify.

```
npm install --save-dev @nuxtjs/storybook

// Then:
Build command: npx nuxt storybook build
Publish directory: storybook-static
```

### What is Expected?

Successfully build of Storybook deployed.

### What is actually happening?

```
1:03:00 AM: info @nuxtjs/storybook v4.0.2
1:03:00 AM: info 
1:03:00 AM: info => Cleaning outputDir: /opt/build/repo/storybook-static
1:03:00 AM: ERR! Failed to load static files, no such directory: /opt/build/repo/static
1:03:00 AM: ERR! Make sure this directory exists, or omit the -s (--static-dir) option.
1:03:00 AM: [fatal] Failed to run command `nuxt-storybook`:
1:03:00 AM: Error: Command failed with exit code 255: nuxt-storybook build
1:03:00 AM: 
1:03:00 AM:    
1:03:00 AM:    │                                                                    │
1:03:00 AM:    │   ✖ Nuxt Fatal Error                                               │
1:03:00 AM:    │                                                                    │
1:03:00 AM:    │   Failed to run command `nuxt-storybook`:                          │
1:03:00 AM:    │   Error: Command failed with exit code 255: nuxt-storybook build   │
1:03:00 AM:    │                                                                    │
1:03:00 AM:    
```

**Comment by silvio-e** [comment]
I'm not sure if my case related but I got a quite similar error on Vercel but with the additional information of missing vue-loader. @lihbr could that be related to #252 where vue-loader got mentioned?

The problem came after upgrading from v3 to 4.0.2

```console

07:24:40.645 | ERR! Module not found: Error: Can't resolve 'vue-loader' in '/vercel/path0'
07:24:40.664 | ERR! ModuleNotFoundError: Module not found: Error: Can't resolve 'vue-loader' in '/vercel/path0'
// ...
07:24:40.665 | ERR!  ModuleNotFoundError: Module not found: Error: Can't resolve 'vue-loader' in '/vercel/path0'
// ...
07:24:40.743 | Error: Command failed with exit code 1: nuxt-storybook build
// ...
07:24:40.748 | ╭──────────────────────────────────────────────────────────────────╮
07:24:40.748 | │                                                                  │
07:24:40.748 | │   ✖ Nuxt Fatal Error                                             │
07:24:40.748 | │                                                                  │
07:24:40.748 | │   Failed to run command `nuxt-storybook`:                        │
07:24:40.748 | │   Error: Command failed with exit code 1: nuxt-storybook build   │
07:24:40.749 | │                                                                  │
07:24:40.749 | ╰──────────────────────────────────────────────────────────────────╯
07:24:40.767 | Error: Command "npx nuxt storybook build" exited with 1
```

**Comment by lihbr** [comment]
Hey, not sure but try deleting your lock file & node modules to give it a fresh install, Storybook often mess up at module resolution when upgrading~

If that still doesn't work this will need investigation.

**Comment by drewbaker** [comment]
@lihbr I deleted lock and modules dir, same error still. My package file if you're curious:

```
{
    "name": "storybook-nuxt",
    "engines": {
        "node": "14.15.4"
    },
    "scripts": {
        "dev": "nuxt",
        "build": "nuxt build",
        "generate": "nuxt generate",
        "start": "nuxt start",
        "storybook": "nuxt storybook",
        "storybook-build": "nuxt storybook build"
    },
    "dependencies": {
        "nuxt": "^2.15.4"
    },
    "devDependencies": {
        "@nuxtjs/storybook": "^4.0.2",
        "@nuxtjs/style-resources": "^1.0.0",
        "core-js": "^3.11.0",
        "eslint": "^7.25.0",
        "eslint-plugin-vue": "^7.9.0",
        "node-sass": "^5.0.0",
        "prettier": "^2.2.1",
        "prettier-eslint": "^12.0.0",
        "sass-loader": "^10.1.1",
        "vue-svg-loader": "^0.16.0",
        "vue-template-compiler": "^2.6.12",
        "webfontloader": "^1.6.28"
    }
}
```

**Comment by drewbaker** [comment]
OK I figured this out!

It was because I had an empty /static folder in my local repo, which meant in GitHub there was no static folder.

So it turns out this module needs a /static folder to work? I think that is still a bug that probably should be fixed, so I'll leave this open.

**Comment by lihbr** [comment]
Oh nice catch! It's quite unlikely that you end up with an empty static folder with Nuxt (you might want at least a `favicon.ico` or `robots.txt`?) but maybe a valid bug? @farnabaz

**Comment by drewbaker** [comment]
Yeah our use case is a as a components library, and we have it running in Nuxt so that we get all the mocks of nuxt-link, fetch etc...

**Comment by silvio-e** [comment]
> Hey, not sure but try deleting your lock file & node modules to give it a fresh install, Storybook often mess up at module resolution when upgrading~

Omg, lol, works for me now. Thanks @lihbr!

**Comment by andreascful** [comment]
Just in case someone is running into this. We just had the same issue but with `/opt/build/repo/public`.
Creating a dummy file in the public folder fixed it.

**Comment by ils-harshn** [comment]
> OK I figured this out!
> 
> It was because I had an empty /static folder in my local repo, which meant in GitHub there was no static folder.
> 
> So it turns out this module needs a /static folder to work? I think that is still a bug that probably should be fixed, so I'll leave this open.

So Should I create a static folder (as working npm run build-storybook & there is not static folder in project), to deploy and If yes, where to create it, in src or root directory or in .storybook?

**Comment by levchenkod** [comment]
> OK I figured this out!
> 
> It was because I had an empty /static folder in my local repo, which meant in GitHub there was no static folder.
> 
> So it turns out this module needs a /static folder to work? I think that is still a bug that probably should be fixed, so I'll leave this open.

Worked for me. I also had to create a file within /stories dir
