### ISSUE TITLE
Process not ending when running yarn run storybook-build

### ISSUE THREAD

**Issue by silvanicus** [nuxt-community/storybook#267]
When I run `yarn run storybook-build` the folder _storybook-static_ is created but the process doesn't finish. I'm building the CI/CD pipeline to build it and wanted to understand why this happens.

The last message is the output directory:

<img width="821" alt="Screen Shot 2021-05-05 at 5 54 59 PM" src="https://user-images.githubusercontent.com/5558412/117219518-0e9bf400-adcb-11eb-82a2-1742dca4244b.png">

**Comment by Decipher** [comment]
I've also encountered this issue. In my case I tracked it down to a custom server middleware that was starting an express listener.
