### ISSUE TITLE
Babel "loose" mode option

### ISSUE THREAD

**Issue by visini** [nuxt-community/storybook#268]
### Version
nuxt-edge@2.16.0-27004333.1676b861
@nuxtjs/storybook@4.0.2

### Steps to reproduce

Newest nuxt-edge version fixes the below console error for nuxt, but still shows up for nuxt-storybook...

> Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-property-in-object since the "loose" mode option was set to "true" for @babel/plugin-proposal-private-methods.The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by exp

See original issue at https://github.com/nuxt/nuxt.js/issues/9224 and fix at https://github.com/nuxt/nuxt.js/pull/9232

**Comment by hendydwip** [comment]
```
build: {
  babel:{
    plugins: [
      ['@babel/plugin-proposal-private-methods', { loose: true }]
    ]
  }
}

```
you can add this on nuxt.config
source : https://stackoverflow.com/questions/67350359/nuxt-js-fresh-install-of-nuxt-2-14-6-contains-babel-loose-option-warnings

**Comment by pi0** [comment]
https://github.com/nuxt/nuxt.js/issues/9224#issuecomment-835742221

**Comment by productfrontenddeveloper** [comment]
@pi0 some problem, 2.15.6
In case of having same issue after upgrading to 2.15.5, please remove lock file (yarn.lock or package.lock.json), node_modules/.cache and .nuxt. If still having issues, please report here.
dont fixed

**Comment by pi0** [comment]
Then we may have same issue in storybook generated webpack/babel config. /cc @farnabaz

**Comment by DominusKelvin** [comment]
Any way to fix this yet?

**Comment by irvv17** [comment]
> ```js
> babel
> ```

This works for me, I also have a babel.config.json file with this config.


`
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "node": true
        }
      }
    ]
  ]
}
`

**Comment by derevandal** [comment]
> > ```js
> > babel
> > ```
> 
> This works for me, I also have a babel.config.json file with this config.
> 
> `{ "presets": [ [ "@babel/preset-env", { "targets": { "node": true } } ] ] }`

not for me :(

**Comment by nigel-codaio** [comment]
Pinning the versions via. yarn resolutions also worked for me -- https://github.com/nuxt/nuxt.js/issues/9224#issuecomment-830237126

**Comment by derevandal** [comment]
Yeah, I've disabled loose mode as well.
and it works fine now

**Comment by productfrontenddeveloper** [comment]
dont fixed
![CleanShot 2021-05-31 at 19 47 05](https://user-images.githubusercontent.com/38668796/120222664-fcd23300-c248-11eb-9fea-0b2013c7fbcc.png)

**Comment by krisimmig** [comment]
I also still have the same message, adding 
```js
plugins: [
  // https://github.com/nuxt/nuxt.js/issues/9224#issuecomment-830577523
  ["@babel/plugin-proposal-private-property-in-object", { loose: true }],
],
```
to nuxt.config.js also didn't change it. Using `"@nuxtjs/storybook": "^4.0.3",`

**Comment by farnabaz** [comment]
The issue exists in Storybook core and seems that they plan to release fix with v6.3.
I've published a patch release to fix this issue.

Do you guys can confirm that this fixes using  `"@nuxtjs/storybook": "^4.0.4"`?

**Comment by fuegoio** [comment]
Using `"@nuxtjs/storybook": "^4.0.4"` and still having the warning :/

**Comment by krisimmig** [comment]
It is working now for me using `nuxtjs/storybook 4.0.4` and not using the `plugin-proposal-private-property-in-object` plugin.
👍

**Comment by hacknug** [comment]
v4.0.4 seems to have fixed the issue for me. Thanks for all the work done! :+1:

**Comment by lorocher** [comment]
> v4.0.4 seems to have fixed the issue for me. Thanks for all the work done! 👍

Same here, keep up the good work 👌

**Comment by productfrontenddeveloper** [comment]
@farnabaz https://github.com/storybookjs/storybook/releases/tag/v7.0.1
