### ISSUE TITLE
stories.ts build problem

### ISSUE THREAD

**Issue by productfrontenddeveloper** [nuxt-community/storybook#274]
### Version
"@nuxtjs/storybook": "^4.0.2",
nuxt:  v2.15.6 
yarn nuxt storybook build

ts
![CleanShot_2021-05-15_at_08 57 39](https://user-images.githubusercontent.com/38668796/118352005-b5b92200-b567-11eb-936d-ce5544566dce.png)

stories.js dont problem
![CleanShot 2021-05-15 at 10 24 07](https://user-images.githubusercontent.com/38668796/118352002-b0f46e00-b567-11eb-990e-7ccad94f23c2.png)

**Comment by productfrontenddeveloper** [comment]
No, I changed ts to js. Now I retested but the problem. how to create ts ? My old examples don't stop. I forgot to write. Also, why does nuxt not appear in the suggestions?
![CleanShot 2021-05-31 at 17 11 33](https://user-images.githubusercontent.com/38668796/120206020-5596d100-c233-11eb-99bd-36472bebaa0c.png)

**Comment by farnabaz** [comment]
I'm not sure what you trying to do.
`@nuxtjs/storybook` does not provide `Story` nor the `Meta` you should import these from Storybook itself

**Comment by productfrontenddeveloper** [comment]
I'm closing this issue. I think you should prepare a ts example and add it to the documentation.
