### ISSUE TITLE
TypeError: Router.use() requires a middleware function but got a undefined

### ISSUE THREAD

**Issue by drewbaker** [nuxt-community/storybook#275]
### Version
@nuxtjs/storybook: 4.0.2
nuxt: 2.15.6

### Reproduction Link
https://github.com/funkhaus/fuxt

First step: Duplicate and rename .example.env to .env.  Then `npm run storybook`.

### Steps to reproduce
The problem is whenever you use a custom defined server-middleware.

In provided repo, just duplicate and rename .example.env to .env.  Then `npm run storybook`.

But in a fresh install of @nuxtjs/storybook, you need to define a custom middleware in your nuxt.config.js file, like so:
```
serverMiddleware: ["~/server-middleware/redirect-trailing-slash.js"],
```

If you comment off the serverMiddleware line, Storybook will run. 

### What is Expected?

Storybook starts and works.

### What is actually happening?

After `npm run storybook`:

```
info => Loading presets
info => Serving static files from /Users/drew/Sites/fuxt/static at /
ERR! TypeError: Router.use() requires a middleware function but got a undefined
ERR!     at Function.use (/Users/drew/Sites/fuxt/node_modules/express/lib/router/index.js:458:13)

ERR!     at addServerMiddleware (/Users/drew/Sites/fuxt/.nuxt-storybook/storybook/middleware.js:12:9)
ERR!     at /Users/drew/Sites/fuxt/.nuxt-storybook/storybook/middleware.js:15:28
ERR!     at Array.forEach (<anonymous>)
ERR!     at module.exports (/Users/drew/Sites/fuxt/.nuxt-storybook/storybook/middleware.js:15:15)
ERR!     at storybookDevServer (/Users/drew/Sites/fuxt/node_modules/@storybook/core-server/dist/cjs/dev-server.js:65:52)
ERR!     at async buildDevStandalone (/Users/drew/Sites/fuxt/node_modules/@storybook/core-server/dist/cjs/build-dev.js:107:31)
ERR!     at async Object.buildDev (/Users/drew/Sites/fuxt/node_modules/@storybook/core-server/dist/cjs/build-dev.js:147:5)
ERR!  TypeError: Router.use() requires a middleware function but got a undefined
ERR!     at Function.use (/Users/drew/Sites/fuxt/node_modules/express/lib/router/index.js:458:13)
ERR!     at addServerMiddleware (/Users/drew/Sites/fuxt/.nuxt-storybook/storybook/middleware.js:12:9)
ERR!     at /Users/drew/Sites/fuxt/.nuxt-storybook/storybook/middleware.js:15:28
ERR!     at Array.forEach (<anonymous>)
ERR!     at module.exports (/Users/drew/Sites/fuxt/.nuxt-storybook/storybook/middleware.js:15:15)
ERR!     at storybookDevServer (/Users/drew/Sites/fuxt/node_modules/@storybook/core-server/dist/cjs/dev-server.js:65:52)
ERR!     at async buildDevStandalone (/Users/drew/Sites/fuxt/node_modules/@storybook/core-server/dist/cjs/build-dev.js:107:31)
ERR!     at async Object.buildDev (/Users/drew/Sites/fuxt/node_modules/@storybook/core-server/dist/cjs/build-dev.js:147:5)
```

**Notes**
If you do actually get Storybook to work, you'll then see this error happen:
https://github.com/nuxt-community/storybook/issues/231

That is due to Storybook not liking the import in `~/pages/_.vue`, and I think is a different bug too.

**Comment by dargmuesli** [comment]
I still have this issue with version `4.0.4`. This is my serverMiddleware:

```
import bodyParser from 'body-parser'

export default {
  serverMiddleware: [
    bodyParser.json(),
    '~/middleware/server/headers.ts',
  ],
}
```

Commenting out either middleware does not fix the issue. Can we reopen this issue or shall I create a new issue?

**Comment by TheMangoTrain** [comment]
I have this error too.

**FAILS - Storybook does not load; same error as op:**
```
 serverMiddleware: [        
        logger({ format: "%date %status %method %url (%time)" }),
        'coexist-parser-proxy',
        '@/middlewareServer/geocode.js',
        '@/middlewareServer/places.js',
        '@/middlewareServer/comms.js',
    ],
```

**WORKS - Storybook loads; but only when I get rid of most of my middleware.**
Most of the offending middleware probably isn't needed for Storybook; what's the best way to make a condition here?

Storybook = Load certain middleware,
Not-storybook = Load all middleware
```
 serverMiddleware: [        
        logger({ format: "%date %status %method %url (%time)" }),
    ],
```
