### ISSUE TITLE
Does not work with @nuxtjs/compositon-api v0.24

### ISSUE THREAD

**Issue by norioxkimura** [nuxt-community/storybook#276]
### Version
@nuxtjs/storybook: v4.0.2
nuxt: 2.15.6

### Reproduction Link
https://github.com/norioxkimura/nuxt-storybook-bug-20210529

### Steps to reproduce
- My example project is using Nuxt, Typescript and Composition-API by [@nuxtjs/composition-api](https://github.com/nuxt-community/composition-api).
```shell-session
$ git clone https://github.com/norioxkimura/nuxt-storybook-bug-20210529
$ cd nuxt-storybook-bug-20210529
$ cd 0.24-ng
$ npm ci
$ npm run storybook
```
- The `<counter>` component implemented using composition-api doesn't work.

![スクリーンショット 2021-05-29 17 48 23](https://user-images.githubusercontent.com/1609737/120065120-ba72ef80-c0aa-11eb-91c7-5f01663a7f51.png)

### What is Expected?
- It worked before 0.24 of @nuxtjs/composition-api.
```shell-session
$ cd ../0.23-ok
$ npm ci
$ npm run storybook
```
![スクリーンショット 2021-05-29 17 43 08](https://user-images.githubusercontent.com/1609737/120065130-c494ee00-c0aa-11eb-9f51-106774a89af9.png)

- Only difference is the version of @nuxtjs/composition-api

### What is actually happening?
- I think the cause of the bug is [the commit](https://github.com/nuxt-community/composition-api/commit/1e423c3783ba2aa70b38a536366623cf8b181515) of @nuxtjs/composition-api.
- The release note of 0.24.0 [says](https://github.com/nuxt-community/composition-api/releases/tag/0.24.0): <q>(outside of Nuxt) only auto-registers plugin if `NODE_ENV == 'test'`</q>
- By temporarily change `node_modules/@nuxtjs/storybook/dist/cli.js` as `process.env.NODE_ENV = 'test';` ([See code](https://github.com/nuxt-community/storybook/blob/1e3a659e102546021d6b56a2618fa03769795b9a/src/cli.ts#L59)), my story of `<counter>` works well again.

**Comment by danielroe** [comment]
@norioxkimura Thanks for the report! This should be fixed in v0.24.3 of `@nuxtjs/composition-api`.
