### ISSUE TITLE
Building and exporting a component library

### ISSUE THREAD

**Issue by armorkram** [nuxt-community/storybook#278]
One of storybook's uses is in [building and distributing a design system/component library](https://storybook.js.org/tutorials/design-systems-for-developers/react/en/distribute/). Been researching on how to do this with nuxt-storybook, such that I end up with a library that can be imported in other projects.

Has anyone succesfully tried this? Or any guidance please on how to approach if I explore making the build configuration? The components are just vue files but it's the nuxt dependencies that could be a challenge.

**Comment by drewbaker** [comment]
Yes we use this as a component library. But we just cut and paste the components into our projects as needed. 

But to do it like you’re describing where you can import components via NPM modules, that’s actually not really a Storybook problem.

Read this:
https://vuejs.org/v2/cookbook/packaging-sfc-for-npm.html

**Comment by armorkram** [comment]
Got it, thanks!
