### ISSUE TITLE
Incorrect storybook version (v1.0.0) is being reported

### ISSUE THREAD

**Issue by altryne** [nuxt-community/storybook#28]
### Version
@nuxtjs/storybook: v1.0.0 
nuxt: v2.14.0

### Steps to reproduce
Install per tutorial, run `npx nuxt storybook` 

### What is Expected?
No warnings

### What is actually happening?
I see a warning that I'm using version 1.0.0 of storybook and version 5.3.19 is available. 
I have a suspicion that this is due to @nuxtjs/storybook being 1.0.0 and somewhere the versions clash

![image](https://user-images.githubusercontent.com/463317/89065354-bb22e400-d328-11ea-9e32-70216d36f8ad.png)

**Comment by farnabaz** [comment]
The module does not check for updates, it's Storybook itself that checks for the new version. It seems that the check URL is not configurable. Disabling is the only option for now.
