### ISSUE TITLE
Storybook Hot Reload keep looping for no reason.

### ISSUE THREAD

**Issue by leeliwei930** [nuxt-community/storybook#293]
### Version
@nuxtjs/storybook: v4.0.3
nuxt: 2.15.7

### Steps to reproduce
When I run the nuxt storybook command, the command starts to boot up the storybook local server.

### What is Expected?
The building progression bar should be completed, and listen on the file saved event that triggers the hot reload

### What is actually happening?
The building progression bar keeps looping and there is no file saved event occurred that trigger the hot reload.

# Notes:
I have tried to upgrade @nuxtjs/storybook to 4.0.4 but the problem still persists.

https://user-images.githubusercontent.com/11514728/122638536-351db080-d127-11eb-97d3-77e6c8a0d53e.mov

**Comment by leeliwei930** [comment]
Just now investigate this issue, the reason it keeps looping due to the JIT mode is enabled in my TailwindCSS config.

**Comment by enzostvs** [comment]
> Just now investigate this issue after numerous times perform reinstallation for all packages, the reason it keeps looping due to the JIT mode is enabled in my TailwindCSS config.
Hi,
have you managed to fix this problem? If so, how?
Thank you

**Comment by leeliwei930** [comment]
> > Just now investigate this issue after numerous times perform reinstallation for all packages, the reason it keeps looping due to the JIT mode is enabled in my TailwindCSS config.
> 
> Hi,
> have you managed to fix this problem? If so, how?
> Thank you

I just comment out the jit mode in tailwind.config.js sound like jit doesn't play well with the storybook.

**Comment by P0TER** [comment]
Same problem and I don't have the jit mod in tailwind.config.js

**Comment by Paalt** [comment]
Commenting out jit mode resolved the issue for me as well. But is this related to this: [](https://github.com/storybookjs/storybook/issues/14342)? If so, bumping storybook to 6.3 might do the trick...

**Comment by P0TER** [comment]
> Commenting out jit mode resolved the issue for me as well. But is this related to this: [storybookjs/storybook#14342](https://github.com/storybookjs/storybook/issues/14342)? If so, bumping storybook to 6.3 might do the trick...

Thanks, this works: https://github.com/storybookjs/storybook/issues/14342#issuecomment-811081265

**Comment by nevadavid** [comment]
> > Commenting out jit mode resolved the issue for me as well. But is this related to this: [storybookjs/storybook#14342](https://github.com/storybookjs/storybook/issues/14342)? If so, bumping storybook to 6.3 might do the trick...
> 
> Thanks, this works: [storybookjs/storybook#14342 (comment)](https://github.com/storybookjs/storybook/issues/14342#issuecomment-811081265)

Can you share your stories config?

Here is mine, but it still looping:
```javascript
const stories = [
	'../components/**/*.stories.@(ts|js)',
];
```

**Comment by Chris-DuCharme** [comment]
I'm having the same issue.  What's puzzling is it is only happening on 1 of 2 projects with the exact same config.  

Disabling JIT is not working for me.

**Comment by P0TER** [comment]
> > > Комментирование режима jit также решило проблему для меня. Но связано ли это с этим: [storybookjs / storybook # 14342](https://github.com/storybookjs/storybook/issues/14342) ? Если это так, то переход сборника рассказов до 6.3 может помочь ...
> > 
> > 
> > Спасибо, это работает: [storybookjs / storybook # 14342 (комментарий)](https://github.com/storybookjs/storybook/issues/14342#issuecomment-811081265)
> 
> Можете ли вы поделиться конфигурацией своих историй?
> 
> Вот мой, но он все еще зацикливается (отключение JIT у меня тоже не работает):
> 
> ```js
> const  stories  =  [ 
> 	'../components/**/*.stories.@(ts|js)' , 
> ] ;
> ```

Sure, here is mine:
```js
storybook: {
  stories: [
    '~/submodules/core/ui/**/*.stories.js',
    '~/submodules/core/ui/**/*.stories.ts',
  ],
},
```

**Comment by nevadavid** [comment]
> > > > Комментирование режима jit также решило проблему для меня. Но связано ли это с этим: [storybookjs / storybook # 14342](https://github.com/storybookjs/storybook/issues/14342) ? Если это так, то переход сборника рассказов до 6.3 может помочь ...
> > > 
> > > 
> > > Спасибо, это работает: [storybookjs / storybook # 14342 (комментарий)](https://github.com/storybookjs/storybook/issues/14342#issuecomment-811081265)
> > 
> > 
> > Можете ли вы поделиться конфигурацией своих историй?
> > Вот мой, но он все еще зацикливается (отключение JIT у меня тоже не работает):
> > ```js
> > const  stories  =  [ 
> > 	'../components/**/*.stories.@(ts|js)' , 
> > ] ;
> > ```
> 
> Sure, here is mine:
> 
> ```js
> storybook: {
>   stories: [
>     '~/submodules/core/ui/**/*.stories.js',
>     '~/submodules/core/ui/**/*.stories.ts',
>   ],
> },
> ```

If I changed to this version, but I get this warn:
```
WARN We found no files matching any of the following globs:
WARN 
WARN ~/components/**/*.stories.@(ts|js)
WARN 
WARN Maybe your glob was invalid?
WARN see: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#correct-globs-in-mainjs
```

And it still looping.

**Comment by nevadavid** [comment]
When I run Nuxt parallel I get this message on the terminal:
```
✔ Client
  Compiled successfully in 1.55s

✔ Server
  Compiled successfully in 2.90s

↻ Updated node_modules/.cache/storybook/dev-server/325c8f456729b912b0d2134054eb7448-41ac79ddc5290d504ad69ef1fe8200a7 
```

Maybe it can help you to find the problem.

**Comment by P0TER** [comment]
> > > > > Комментирование режима jit также решило проблему для меня. Но связано ли это с этим: [storybookjs / storybook # 14342](https://github.com/storybookjs/storybook/issues/14342) ? Если это так, то переход сборника рассказов до 6.3 может помочь ...
> > > > 
> > > > 
> > > > Спасибо, это работает: [storybookjs / storybook # 14342 (комментарий)](https://github.com/storybookjs/storybook/issues/14342#issuecomment-811081265)
> > > 
> > > 
> > > Можете ли вы поделиться конфигурацией своих историй?
> > > Вот мой, но он все еще зацикливается (отключение JIT у меня тоже не работает):
> > > ```js
> > > const  stories  =  [ 
> > > 	'../components/**/*.stories.@(ts|js)' , 
> > > ] ;
> > > ```
> > 
> > 
> > Sure, here is mine:
> > ```js
> > storybook: {
> >   stories: [
> >     '~/submodules/core/ui/**/*.stories.js',
> >     '~/submodules/core/ui/**/*.stories.ts',
> >   ],
> > },
> > ```
> 
> If I changed to this version, but I get this warn:
> 
> ```
> WARN We found no files matching any of the following globs:
> WARN 
> WARN ~/components/**/*.stories.@(ts|js)
> WARN 
> WARN Maybe your glob was invalid?
> WARN see: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#correct-globs-in-mainjs
> ```
> 
> And it still looping.


Maybe this will help, tsconfig.json:
```js
{
  "compilerOptions": {
     ...
    "paths": {
       "~/*": [
         "./*"
       ],
    },
    ...
}
```

**Comment by nevadavid** [comment]
> > > > > > Комментирование режима jit также решило проблему для меня. Но связано ли это с этим: [storybookjs / storybook # 14342](https://github.com/storybookjs/storybook/issues/14342) ? Если это так, то переход сборника рассказов до 6.3 может помочь ...
> > > > > 
> > > > > 
> > > > > Спасибо, это работает: [storybookjs / storybook # 14342 (комментарий)](https://github.com/storybookjs/storybook/issues/14342#issuecomment-811081265)
> > > > 
> > > > 
> > > > Можете ли вы поделиться конфигурацией своих историй?
> > > > Вот мой, но он все еще зацикливается (отключение JIT у меня тоже не работает):
> > > > ```js
> > > > const  stories  =  [ 
> > > > 	'../components/**/*.stories.@(ts|js)' , 
> > > > ] ;
> > > > ```
> > > 
> > > 
> > > Sure, here is mine:
> > > ```js
> > > storybook: {
> > >   stories: [
> > >     '~/submodules/core/ui/**/*.stories.js',
> > >     '~/submodules/core/ui/**/*.stories.ts',
> > >   ],
> > > },
> > > ```
> > 
> > 
> > If I changed to this version, but I get this warn:
> > ```
> > WARN We found no files matching any of the following globs:
> > WARN 
> > WARN ~/components/**/*.stories.@(ts|js)
> > WARN 
> > WARN Maybe your glob was invalid?
> > WARN see: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#correct-globs-in-mainjs
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And it still looping.
> 
> Maybe this will help, tsconfig.json:
> 
> ```js
> {
>   "compilerOptions": {
>      ...
>     "paths": {
>        "~/*": [
>          "./*"
>        ],
>     },
>     ...
> }
> ```

It didn't help me.

**Comment by dargmuesli** [comment]
It's not hot reloading anymore with `@nuxtjs/storybook` v4.1.1 and `tailwindcss` v2.2.4 for me anymore.

**Comment by leeliwei930** [comment]
> It's not hot reloading anymore with `@nuxtjs/storybook` v4.1.1 and `tailwindcss` v2.2.4 for me anymore.

Problem solved after performing the update for these version
