### ISSUE TITLE
ERROR  No pages directory found

### ISSUE THREAD

**Issue by altryne** [nuxt-community/storybook#30]
### Version
@nuxtjs/storybook: ex: v1.0.0 
nuxt: v2.14.0

### Steps to reproduce
1. Fork https://github.com/nuxt-community/storybook/tree/master/examples/manual-setup
1. `npm i` 
1. `npx nuxt storybook` 

### What is Expected?
Storybook runs

### What is actually happening?
Nuxt complains that it can't find `pages` directory in the `/storybook` directory

![image](https://user-images.githubusercontent.com/463317/89072887-a77e7a00-d336-11ea-94c6-9b2e699298e6.png)

**Comment by farnabaz** [comment]
It seems that nuxt cannot detect `storybook` command because it conflicts with `storybook` directory for manual setup.  
@pi0 Is there a clean solution to avoid this conflict or we need to change the manual setup directory to something other than `storybook`

**Comment by pi0** [comment]
Indeed that's a limitation with nuxt cli because of `nuxt dev` shortcut. We should whitelist storybook here: https://github.com/nuxt/nuxt.js/blob/dev/packages/cli/src/run.js#L31

**Comment by farnabaz** [comment]
@pi0 What about checking for `nuxt.config.(js|ts)` inside `argv[0]` instead of directory existance?

```js
if (!cmd && (!argv[0] || argv[0][0] === '-' || fs.existsSync(`${argv[0]}$[path.sep}nuxt.config.ts`) || fs.existsSync(`${argv[0]}$[path.sep}nuxt.config.js`))) {
...
}
```

**Comment by altryne** [comment]
@farnabaz I see that this was mentioned in a merged commit but the issue still replicates locally with `"@nuxtjs/storybook": "^1.2.0"` and nuxt `"nuxt": "^2.14.1",`

**Comment by altryne** [comment]
oh I re-read documentation and now if I run `npx nuxt-storybook` instead of `npx nuxt storybook` this error doesn't show up.
