### ISSUE TITLE
v4.1.0 Error: Cannot find module 'vue-loader/lib/plugin'

### ISSUE THREAD

**Issue by dargmuesli** [nuxt-community/storybook#300]
Upgrading v4.0.4 to v4.1.0 yield an `Error: Cannot find module 'vue-loader/lib/plugin'` error: https://github.com/maevsi/maevsi/runs/2988094445?check_suite_focus=true#step:6:1073

**Comment by yshrsmz** [comment]
Same here, storybook doesn't render anything.

**Comment by ahobbit** [comment]
It seems to be related to this issue https://github.com/storybookjs/storybook/issues/14623

**Comment by farnabaz** [comment]
This should be fixed in https://github.com/nuxt-community/storybook/releases/tag/v4.1.1

I've frizzed vue-loader in 15.x, until it fixes in Storybook
