### ISSUE TITLE
Stories in static build are empty

### ISSUE THREAD

**Issue by tobiasdiez** [nuxt-community/storybook#312]
### Version
@nuxtjs/storybook: 4.1.1
nuxt: 2.15.7

### Reproduction Link

https://github.com/JabRef/JabRefOnline/pull/362

### Steps to reproduce

Run `nuxt storybook build`.

### What is Expected?

No error in console and stories show up.

### What is actually happening?

The static storybook instance is build successfully, however all stories are empty and the following error is displayed in the console:
> Failed to generate dynamic story source: TypeError: lookupStoryInstance(...) is null

The call that triggers this is at https://github.com/storybookjs/storybook/blob/343ec61525b63fc9d1b3361603a981b18945dec1/addons/docs/src/frameworks/vue/sourceDecorator.ts#L51.
The `lookupStoryInstance` is however in the same file, so I guess webpack decides to erase it for some reason during build.

**Comment by Suv4o** [comment]
I'm facing the same issue.  Nuxt: 2.15.7, @nuxtjs/storybook: 4.1.1.

When I run locally wirh `npx nuxt storybook` all works fine. But when I run build with `npx nuxt storybook build` it builds successfully, however the components aren't shown. Any Idea why this is happening?

<img width="1014" alt="Screen Shot 2021-08-13 at 11 23 21 pm" src="https://user-images.githubusercontent.com/56303591/129363641-d57ed31d-e6f7-42a1-bdb6-0b985e20b281.png">
<img width="1022" alt="Screen Shot 2021-08-13 at 11 20 37 pm" src="https://user-images.githubusercontent.com/56303591/129363650-54bffeb2-3ade-43df-8cd5-a2b69399818b.png">

**Comment by desiboli** [comment]
I'm facing the exact same issue!

**Comment by tobiasdiez** [comment]
@Suv4o @desiboli @farnabaz Did you find a workaround for this issue?

**Comment by ngonam22** [comment]
I'm suffering the same problem!
The root div has only this placeholder comment:
`<!--function(a,b,c,d){return createElement(vm,a,b,c,d,!0)}-->`

Any update?

**Comment by farnabaz** [comment]
This should be fixed in #335 and will release in 4.2.
I close this issue now, feel free to reopen it, if 4.2 does not fix the issue.

**Comment by tobiasdiez** [comment]
Thanks @farnabaz! When do you expect to release 4.2 and is there a possibility to try the latest dev version (I couldn't find a `-edge` package on npm)?

**Comment by farnabaz** [comment]
Just released v4.2

**Comment by tobiasdiez** [comment]
Thanks a lot! It is indeed working now for me. Nice start into the week ;-)
