### ISSUE TITLE
[bug][@nuxtjs/composition-api][build] Build does not show canvas when composition-api is installed

### ISSUE THREAD

**Issue by Rigo-m** [nuxt-community/storybook#318]
### Version
@nuxtjs/storybook: ^4.1.1
nuxt: ^2.15.7
@nuxtjs/composition-api: ^0.27.0

### Reproduction Link
https://github.com/Rigo-m/text-storybook-composition-api

### Steps to reproduce
Execute `yarn storybook:build` with `@nuxtjs/composition-api` inserted in `buildModules` -> no components are shown in canvas
If you remove composition-api from `buildModules` everything looks good again

### What is Expected?
Storybook should work with `@nuxtjs/composition-api`

### What is actually happening?
Storybook does not work alongside `@nuxtjs/composition-api`

**Comment by ahmadalfy** [comment]
I am having the same issue

**Comment by Rigo-m** [comment]
@farnabaz sorry for tagging you directly. This issue is quite blocking for any project that relies on composition-api and storybook. Did you take a look at it by chance? Thanks for your attention

**Comment by farnabaz** [comment]
Thank you @Rigo-m for pinging me, and Sorry for the late response.
Seems that composition-api module tries to change `Vue` alias and it cause the issue.

**Comment by sppmstar** [comment]
I'm still running into this issue with @nuxt/composition-api 0.31.0 and @nuxt/storybook 4.2.0 ... :(

**Comment by sppmstar** [comment]
reverting to version 0.23.1 of @nuxtjs/composition-api seem to solve the issue...
