### ISSUE TITLE
Decorators not working with `nuxt storybook build`

### ISSUE THREAD

**Issue by hitochan777** [nuxt-community/storybook#322]
### Version
@nuxtjs/storybook: v4.1.1
nuxt: v2.15.7

### Reproduction Link
https://github.com/hitochan777-misc/nuxt-storybook-sandbox

### Steps to reproduce
1. `npm ci`
2. `npx nuxt storybook build`
3. `npx serve storybook-static`

### What is Expected?
`decorators` is set to `<v-app><story /></v-app>` so each story should be styled according to the theme configuration of vuetify.
In this case dark mode is set to true, thus the background should be black.

The background is black when run as dev server (e.g., `npx nuxt storybook`), as shown below.
![image](https://user-images.githubusercontent.com/6002787/133633059-b5d57536-0355-4a28-966c-b13a6c2a93eb.png)

### What is actually happening?

The background is white instead of black.
![image](https://user-images.githubusercontent.com/6002787/133632606-9f17da63-5cbb-43ee-aa4c-8d8fca37d9c5.png)

Checking the source code in sources Tab on my browser, the tag `<v-app>` is still there, which is supposed to be compiled.

**Comment by usco-otsuki** [comment]
Sorry I found a similar (or duplicate) issue #166.
The problem was v-app was not recognized during the build and removed from the bundle by treeshake.

**Comment by hitochan777** [comment]
I seems this issue is duplicate of #166.
`treeShake` is enabled by default in @nuxtjs/vuetify module and template strings in decorators options is not recognized during the build, thus `v-app` is not transpiled.
