### ISSUE TITLE
Error: No configuration files have been found in your configDir

### ISSUE THREAD

**Issue by FlipFloop** [nuxt-community/storybook#325]
Currently using Nuxt 2.15.3 and v4.1.1 of this package.

I followed the website's documentation and get that error along with:
Storybook needs either a "main" or "config" file.

**Comment by Eddie344** [comment]
@FlipFloop hello! Please, can you tell how to fix it?

**Comment by FlipFloop** [comment]
I don't remember :/ sorry!
