### ISSUE TITLE
This story is not configured to handle controls. Learn how to add controls

### ISSUE THREAD

**Issue by FlipFloop** [nuxt-community/storybook#326]
### Version
@nuxtjs/storybook: 
nuxt: 

### Steps to reproduce
Follow docs at [https://storybook.nuxtjs.org/getting-started/usage](https://storybook.nuxtjs.org/getting-started/usage)

### What is Expected?

For storybook controls to work fine.

### What is actually happening?

Storybook controls is not added, and there is no explanation on how to add them.

**Comment by farnabaz** [comment]
Please take a look at addon-controls example. here: https://github.com/nuxt-community/storybook/blob/master/examples/addon-controls/components/MyButton.stories.js

**Comment by FlipFloop** [comment]
@farnabaz Brilliant! Thank you!
