### ISSUE TITLE
Version 4.2.0 requires manual installation of specific css-loader version

### ISSUE THREAD

**Issue by DerYeger** [nuxt-community/storybook#341]
### Version
@nuxtjs/storybook: 4.2.0
nuxt: 2.15.8

### Reproduction Link
[This specific commit](https://github.com/DerYeger/noted/tree/71eda04bf3ddb5d9acdfce37870f0d9002b7c81e) has updated `@nuxtjs/storybook` to 4.2.0 without also installing `css-loader` .
The logs of the failed pipeline can be found [here](https://github.com/DerYeger/noted/runs/4190218465?check_suite_focus=true).

### Steps to reproduce

Update to `@nuxtjs/storybook` to version 4.2.0.

### What is Expected?

No breaking changes, since it's only a minor update.

### What is actually happening?

`nuxt build` fails with the above-linked error messages.
The warning `css-loader@3.6.0 is installed but >=4.2.0 is expected` is printed.
Manually installing `css-loader` 4.2.0 fixes the issue.

**Comment by theolavaux** [comment]
Also had this issue in my project, is it in the process to be solved ?

**Comment by seibert-io** [comment]
Adding to this: @nuxtjs/storybook v 4.2.0 bumbed the css-loader dependency from ^5.2.6 to ^6.5.1. As css-loader 6.0.0 dropped support for webpack 4 this should be considered a breaking change to @nuxtjs/storybook.
