### ISSUE TITLE
Immer and trim high/critical severity security alerts

### ISSUE THREAD

**Issue by alexcroox** [nuxt-community/storybook#346]
![image](https://user-images.githubusercontent.com/1065835/142294342-47d87315-4041-4e4a-bfe3-5e85a262762f.png)

![image](https://user-images.githubusercontent.com/1065835/142294399-901ae2e2-4c6d-43ad-8266-aea59a4774c1.png)

![image](https://user-images.githubusercontent.com/1065835/142294416-8744965a-1b9a-45f7-b772-66f7c363e7c2.png)

**Comment by solidevolution** [comment]
Any updates here?

**Comment by rlam3** [comment]
@farnabaz Hey we as a community know you are busy but would really love for this security alert to be patched. Thank you!
