### ISSUE TITLE
Update from 4.1.1 to 4.2.0 doesn't work with mdx files

### ISSUE THREAD

**Issue by solidevolution** [nuxt-community/storybook#349]
### Version
@nuxtjs/storybook: 4.2.0
nuxt: 2.15.8

### Reproduction Link
https://codesandbox.io/s/infallible-cherry-l4yxk?file=/.storybook/main.js

### Steps to reproduce

Setup storybook like the docs "Manual usage"
Add a mdx file with Meta, Story or Canvas
Update @nuxtjs/storybook from 4.1.1 to 4.2.0

### What is Expected?

Styleguide works

### What is actually happening?

```
ERROR in ./styleguide/0_introduction.stories.mdx
Module not found: Error: Can't resolve '@storybook/addon-docs' in '/Users/xxx/Entwicklung/xxx/styleguide'
 @ ./styleguide/0_introduction.stories.mdx 18:0-63 93:15-25
 @ ./styleguide sync nonrecursive ^\.\/(?:(?!\.)(?=.)[^/]*?\.mdx)$
 @ ./.storybook/generated-stories-entry.js
 @ multi ./.nuxt-storybook/composition-api/register.js ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/globals/globals.js ./.storybook/storybook-init-framework-entry.js ./node_modules/@storybook/addon-essentials/node_modules/@storybook/addon-docs/dist/esm/frameworks/common/config.js-generated-other-entry.js ./node_modules/@storybook/addon-essentials/node_modules/@storybook/addon-docs/dist/esm/frameworks/vue/config.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addArgs.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addParameter.js-generated-other-entry.js ./node_modules/@storybook/addon-measure/dist/esm/preset/preview.js-generated-other-entry.js ./node_modules/storybook-addon-outline/dist/esm/preset/addDecorator.js-generated-other-entry.js ./.storybook/preview.js-generated-config-entry.js ./.storybook/generated-stories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined
```

**Comment by solidevolution** [comment]
Any updates here?

**Comment by solidevolution** [comment]
We temporary solved this by importing the same version of the @storybook/addon-docs Module. Looks like this is a npm 8 resolution problem.

To reach mdx support, install those:

`
npm install --save-dev @nuxtjs/storybook@~4.2.0 @storybook/addon-docs@~6.3.13
`

**Comment by PeteJStewart** [comment]
> We temporary solved this by importing the same version of the @storybook/addon-docs Module. Looks like this is a npm 8 resolution problem.
> 
> To reach mdx support, install those:
> 
> `npm install --save-dev @nuxtjs/storybook@~4.2.0 @storybook/addon-docs@~6.3.13`
> 
> More infos: [storybookjs/storybook#14429](https://github.com/storybookjs/storybook/issues/14429)

This partly worked for me.
I had no docs working after upgrading to 4.2, but after downgrading everything to 6.3.13 I now have docs for each story.
I still cant seem to get .mdx files to show up, but at least there's some docs.

I did the following:

```bash
npm remove @storybook/addon-a11y @storybook/addon-actions @storybook/addon-essentials @storybook/addon-links @storybook/addons @storybook/theming @storybook/vue


npm i -D @storybook/addon-a11y@~6.3.13 @storybook/addon-actions@~6.3.13 @storybook/addon-essentials@~6.3.13 @storybook/addon-links@~6.3.13 @storybook/addons@~6.3.13 @storybook/theming@~6.3.13 @storybook/vue@~6.3.13 @storybook/addon-docs@~6.3.13
```

I had already removed `@storybook/addon-docs` but had to take everything back to the same version for it to work.

**Comment by farnabaz** [comment]
This should be fixed in https://github.com/nuxt-community/storybook/pull/357.

Feel free to reopen it if issue proceed in next version.

**Comment by solidevolution** [comment]
Hello, I've tried to update today again from 4.2.0 to 4.3.1

* .mdx files do show any vue components in docs tab. (Inspect show the component)
* it seems that preview.js don't work (no parameters for sorting, no globalTypes, no layout or view mode changes)
