### ISSUE TITLE
Upgrade to Storybook 6.4

### ISSUE THREAD

**Issue by marekbrze** [nuxt-community/storybook#354]
### Description

Right now, Nuxt/Storybook module uses Storybook 6.3, but the current version is 6.4 and it introduces exciting new features:

- ▶️ Interactive stories to simulate user behavior and tools to debug it ([Interactive stories](https://storybook.js.org/blog/interactive-stories-beta/))
- ⚡️ On-demand architecture for smaller builds and faster load times ([On-demand architecture](https://storybook.js.org/blog/storybook-on-demand-architecture/))
- ⛸ Automigrate + versioned documentation for easier upgrades
- Component Story Format 3.0 ([CSF 3.0](https://storybook.js.org/blog/component-story-format-3-0/))

### Solution

- Upgrade Storybook dependencies to v6.4.x

**Comment by existe-deja** [comment]
related to https://github.com/storybookjs/storybook/issues/16944
