### ISSUE TITLE
Add Gitpod configuration

### ISSUE THREAD

**Issue by Decipher** [nuxt-community/storybook#355]
### Is your feature request related to a problem? Please describe.

As a contributor I want this project to have gitpod prebuilds ready for development so I can contribute easily.

### Describe the solution you'd like

- [ ] Add `.gitpod.yml` with
  - [ ] VS code extensions: editorconfig, vetur, etc
  - [ ] `init` task to install and build the codebase
  - Note, prebuilds require additional setup: https://www.gitpod.io/docs/prebuilds#github

### Additional context

- https://www.gitpod.io/docs/config-start-tasks

**Comment by farnabaz** [comment]
Ref: https://github.com/nuxt-community/storybook/pull/356
