### ISSUE TITLE
Nuxt Bridge + nuxt/storybook 

### ISSUE THREAD

**Issue by DamianHenisz** [nuxt-community/storybook#359]
### Version
@nuxtjs/storybook:  v4.2.0
"nuxt-edge": "latest",
"@nuxt/core-edge": "^2.16.0-27358576.777a4b7f",
 "@nuxt/bridge": "npm:@nuxt/bridge-edge@^3.0.0-27376999.6abf75d",###
  
Hi guys, 
I have errors when used nuxt-bridge with storybook.

### Steps to reproduce
The first error is when I use in my setup() in nuxt/layout/default.

`const { $store } = useNuxtApp();`

Second error when is I had commented const { $store } = useNuxtApp(); 
I used only `useLazyAsyncData()`  gets next error. 

### What is actually happening?
That is, it does not recognize the getCurrentInstance () method in this new API.

I tried use 
npx nuxt storybook 
npx nuxt-storybook

It is the same in all of them.

<img width="260" alt="storybook store" src="https://user-images.githubusercontent.com/32622405/152162190-a436fb70-771d-4ed2-9a4e-b152e67ab551.PNG">
<img width="665" alt="storybook store 2" src="https://user-images.githubusercontent.com/32622405/152162196-2c33fcae-c177-4f4b-957b-1bce1a0513d9.PNG">
<img width="370" alt="storybook intance" src="https://user-images.githubusercontent.com/32622405/152162200-ff0b6790-b899-4343-baee-cc011572bddd.PNG">
<img width="656" alt="storybook instance 2" src="https://user-images.githubusercontent.com/32622405/152162209-4751ecf1-c3b3-4144-88ce-7591dad20ff3.PNG">

**Comment by Rigo-m** [comment]
Related: https://github.com/nuxt-community/storybook/issues/351

**Comment by bmulholland** [comment]
You can't even add a runtime config var `isStorybook` to workaround the issue: `useRuntimeConfig` _also_ throws this error.

**Comment by pi0** [comment]
Would you please please help create a reproduction sandbox? I can quickly check 🙏🏼

**Comment by bmulholland** [comment]
@pi0 someone created one over at #351: https://stackblitz.com/edit/nuxt-starter-yjbds9?file=components%2FTutorial.stories.js

**Comment by pi0** [comment]
Here is updated sandbox for reproduction: https://stackblitz.com/edit/nuxt-starter-dgxcej?file=package.json

**Comment by pi0** [comment]
#405 should bring basic bridge support. /cc @farnabaz 

In the meantime, you can use this workaround inside `nuxt.config`:

```js
import { defineNuxtConfig } from '@nuxt/bridge';


export default defineNuxtConfig({
  hooks: {
    // Workaround for https://github.com/nuxt-community/storybook/pull/405
    'modules:done'(nuxt) {
      for (const p of nuxt.options.plugins) {
        if (p.mode && p.mode === 'all') {
          delete p.mode;
        }
      }
    }
  },
```

**Comment by yshrsmz** [comment]
@pi0 @farnabaz Hi,this seems to be not fixed for v4, which we need to actually work with Nuxt/Bridge.

**Comment by yshrsmz** [comment]
@farnabaz I've opened #466 to fix the problem. Please take a look.
