### ISSUE TITLE
Error onNuxtReady with @nuxt/content

### ISSUE THREAD

**Issue by giticon** [nuxt-community/storybook#36]
### Version
@nuxtjs/storybook: v1.0.0
@nuxtjs/content: v1.5.3
nuxt: v2.14.0

### Error in console

`Uncaught TypeError: window.onNuxtReady is not a function
    NuxtJS 3
        default
        plugins
        js
    Webpack 7
        __webpack_require__
        fn
        0
        __webpack_require__
        checkDeferredModules
        webpackJsonpCallback
        <anonymous>
plugin.client.js:37
    NuxtJS 2
    forEach self-hosted:216
    js NuxtJS
    Webpack 7
`

### What is Expected?

Storybook runs

### What is actually happening?

![immagine](https://user-images.githubusercontent.com/27739275/89132036-858d1f00-d511-11ea-8b5b-ffb54da592c3.png)

**Comment by farnabaz** [comment]
Fixed in [v1.1.0](https://github.com/nuxt-community/storybook/releases/tag/v1.1.0)
