### ISSUE TITLE
Doesn't work with @nuxt/postcss8

### ISSUE THREAD

**Issue by drewbaker** [nuxt-community/storybook#361]
We have multiple projects that use @nuxt/postcss8: https://github.com/nuxt/postcss8

Following this guide for an addon to support PostCSS v8 doesn't seem to work: https://storybook.js.org/addons/@storybook/addon-postcss

I'd love to know how to get this to work with PostCSS 8.

**Comment by Decipher** [comment]
On the contrary, I've found that it doesn't work without @nuxtjs/postcss8.

My steps:
1. Install Nuxt via `npx create-nuxt-app`
2. Install @nuxtjs/storybook `yarn add --dev @nuxtjs/storybook postcss@latest`
3. Attempt to run storybook: `npx nuxt storybook`
4. Error.
5. Uninstall postcss: `yarn remove postcss`
6. Add @nuxtjs/postcss8 as per https://github.com/nuxt/postcss8 (Make sure to update nuxt.config.js)
7. Run, all good

**Comment by drewbaker** [comment]
OK, so what I figured out was that I needed to also add the postCSS plugins twice in my nuxt.config.js file. Like this:

```
build: {
       postcss: {
            plugins: {
                "postcss-for": {},
                "postcss-nested": {},
                "postcss-custom-media": {},
                "postcss-hexrgba": {},
            },
        },
},
storybook: {
        addons: [
            "@storybook/addon-postcss",
            {
                name: "@storybook/addon-postcss",
                plugins: {
                    "postcss-for": {},
                    "postcss-nested": {},
                    "postcss-custom-media": {},
                    "postcss-hexrgba": {},
                },
            },
        ],
}
```
