### ISSUE TITLE
nuxt storybook build --output-dir

### ISSUE THREAD

**Issue by ghengeveld** [nuxt-community/storybook#37]
Currently the `nuxt storybook build` command does not accept the `--output-dir` flag. This causes `chromatic` to fail because it attempts to provide that flag to the `build-storybook` script.

I would expect `nuxt storybook build` to simply forward any flags directly to `build-storybook`.

For Chromatic, there's a workaround available, but that's not ideal:
- Run `nuxt storybook build` manually before running Chromatic
- Run `chromatic` with the `--storybook-build-dir storybook-static` flag

PS I'm the maintainer of [chromatic-cli](https://github.com/chromaui/chromatic-cli). This issue was reported by one of our users.

**Comment by mkalayci35** [comment]
+ 1

**Comment by farnabaz** [comment]
> I would expect `nuxt storybook build` to simply forward any flags directly to `build-storybook`.  

Currently, `@nuxtjs/storybook` does not accept any flags. But supporting `storybook` flags is inevitable.  
I'll put this in v1.2.0 milestones.

**Comment by productfrontenddeveloper** [comment]
@farnabaz @gaetansenn 

![CleanShot 2021-05-15 at 14 45 18](https://user-images.githubusercontent.com/38668796/118359449-3427bb00-b58c-11eb-9511-ee858d2c491b.png)
