### ISSUE TITLE
Args/Controls broken

### ISSUE THREAD

**Issue by Decipher** [nuxt-community/storybook#373]
### Version
@nuxtjs/storybook: 4.3.0
nuxt: 2.15.8

### Reproduction Link
https://gitpod.io/#https://github.com/druxt/druxt.js/pull/467

### Steps to reproduce
1. Wait for Gitpod to start
2. `cd examples/nuxt/druxt-site`
3. `yarn && yarn storybook`
4. Wait for Storybook to start
5. Open Storybook (cmd/ctrl click the `localhost:3003` link)
6. Visit the following story: `/?path=/story/druxt-entity-node-article-view-displays--default`
7. Use Vue developer tools to inspect the Root Vue component

### What is Expected?
The `data.STORYBOOK_VALUES` should contain Args or values from controls.

### What is actually happening?
<img width="411" alt="image" src="https://user-images.githubusercontent.com/161090/156960803-8aaa1deb-60e4-46e4-846d-74b658421fe9.png">

### Additional context

The issue appears to only effect Canvas stories, not Inline stories.

**Comment by Decipher** [comment]
### Workaround

Downgrade **nuxt/storybook** to 4.2.0: `yarn remove @nuxtjs/storybook && yarn add -D @nuxtjs/storybook@4.2.0 && yarn storybook`

<img width="411" alt="image" src="https://user-images.githubusercontent.com/161090/156961129-3fa751ba-c0e7-44a0-bdb4-c8b85b67ee60.png">

**Comment by verstoff** [comment]
Looks like the library is based on [@storybook/vue 6.3 package code](https://github.com/storybookjs/storybook/blob/v6.3.13/app/vue/src/client/preview/render.ts) 
It had been ok on 4.2, but in 4.3 storybook was updated on the 6.4 [without codebase changes](https://github.com/nuxt-community/storybook/blob/bfe7bb0b6ae250dd4ca55c10fd525aaa87e65e5b/storybook/nuxt-entry.js#L131) according to [@storybook/vue 6.4](https://github.com/storybookjs/storybook/blob/v6.4.19/app/vue/src/client/preview/render.ts). As i can see, they have different render function arguments interface.

**Comment by solidevolution** [comment]
I have a similar problem after upgrading from storybook 6.3 to 6.4.

- All components are missing the default args, so most components have no property values
- All mdx files are missing their vue components (but without any error)
- All story sorting are missing (storybook options "storySort")

I will revert to 6.3 and try again later.

**Comment by mrillusion** [comment]
I am also noticing this issue in 4.3.0, downgrading to 4.2.0 worked for me in the meantime.

**Comment by farnabaz** [comment]
This resolved in #378 and released in https://github.com/nuxt-community/storybook/releases/tag/v4.3.1.

Feel free to reopen, if issue persists.
