### ISSUE TITLE
Vue components props are empty

### ISSUE THREAD

**Issue by krisimmig** [nuxt-community/storybook#382]
### Version
@nuxtjs/storybook: 4.3.0
nuxt: 2.15.8

### Reproduction Link
https://github.com/krisimmig/nuxt_sb

### Steps to reproduce
Git clone this repo, install with `yarn install` and run storybook with `yarn storybook`.

### What is Expected?
The `TestComponent.stories.js` file has the `testProp` set to `Foo`, expected is to see this value in storybook as well when the component is rendered.

### What is actually happening?
You can see that the prop `testProp` in the TestComponent is not filled in storybook.

**Comment by farnabaz** [comment]
This resolved in #378 and releases in https://github.com/nuxt-community/storybook/releases/tag/v4.3.1

Feel free to reopen, if issue persists.
