### ISSUE TITLE
Storybook V6 Support

### ISSUE THREAD

**Issue by farnabaz** [nuxt-community/storybook#39]
Currently `@nuxtjs/storybook` works with Stoyebook v5 and at the time Storybook team working for the next major release v6.  
Let's discuss here about moving to Storybook v6.

**Comment by mkalayci35** [comment]
+1

**Comment by shilman** [comment]
Thanks for initiating @farnabaz and for the awesome work you and your team have done on the new preset!

Here's what I can share on SB6:
- Release is scheduled for Aug 10 https://github.com/storybookjs/storybook/issues/9311
- Migration documented in [MIGRATION.md](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#from-version-53x-to-60x)
- I'll share a user friendly migration post tomorrow once it's live

If you have any questions about Storybook or V6, please feel free to reach out here or directly!

**Comment by farnabaz** [comment]
Thank you @shilman, for your kind words and support.  
I think we could manage to release a new version with SB6 on the same date.
I'll create a Draft PR based on SB6 docs.
Very excited about Storybook 6 with awesome features 👍 👍

**Comment by shilman** [comment]
And here’s the migration guide: https://link.medium.com/19v4W24rI8

**Comment by mkalayci35** [comment]
@farnabaz release storybook [v.6.0.0 ](https://github.com/storybookjs/storybook/releases/tag/v6.0.0)

**Comment by shilman** [comment]
That was fast!! 🚀
