### ISSUE TITLE
Build-storybook command doesn't work/exist

### ISSUE THREAD

**Issue by VitorGouveia** [nuxt-community/storybook#396]
### Version
@nuxtjs/storybook: 4.3.2
nuxt: 2.15.8

### Steps to reproduce
run
```bash
yarn nuxt build-storybook
```

### What is Expected?
The build-storybook command to run just like a normal installation of storybook, thus exporting the whole storybook to a `storybook` folder with the static files inside

### What is actually happening?
```bash
 FATAL  Failed to run command nuxt-build-storybook:                                                                                                
Error: Command failed with ENOENT: nuxt-build-storybook
spawn nuxt-build-storybook ENOENT
```

**Comment by alfredourboro** [comment]
Hi I'm running into this same issue did you have a fix for this?
