### ISSUE TITLE
Override nuxt.config

### ISSUE THREAD

**Issue by pimlie** [nuxt-community/storybook#4]
Some nuxt.config options might not be that useful for a storybook build but do influence the webpack config. See #3, a solution for that specific example could also be to just disable extractCSS for storybook builds

**Comment by farnabaz** [comment]
Thank you @pimlie 
Fixed in https://github.com/nuxt-community/storybook/commit/3ed5d3c2938c75d2ed8286577ba532f7aab1cd4a
