### ISSUE TITLE
Need ability to add custom head tags

### ISSUE THREAD

**Issue by bbusch19** [nuxt-community/storybook#44]
### Is your feature request related to a problem? Please describe.
In Storybook, there is an option to add custom tags to the head. I have not been able to figure out how to do this with nuxt storybook. I need to be able to add certain global variables, but I can't find an option to do so. 

### Describe the solution you'd like
It would be great to be able to add custom scripts to the header like you can with Storybook. 
[https://storybook.js.org/docs/configurations/add-custom-head-tags/](https://storybook.js.org/docs/configurations/add-custom-head-tags/)

### Describe alternatives you've considered
I have attempted to set up Storybook with nuxt on its own, but that comes with many other problems that Id rather not deal with.

**Comment by hacknug** [comment]
I had this working on my custom Storybook installation but would also love to know how to set it up using the module.

**Comment by arpadgabor** [comment]
+1 but for [body](https://storybook.js.org/docs/configurations/add-custom-body/).

**Comment by farnabaz** [comment]
For now, the best option is ejecting Storybook config, see: [manual setup](https://storybook.nuxtjs.org/manual-setup)

**Comment by bbusch19** [comment]
> For now, the best option is ejecting Storybook config, see: [manual setup](https://storybook.nuxtjs.org/manual-setup)

This seems to work for me. I can add `preview-head.html` to the `storybook` directory and the result is as expected.
