### ISSUE TITLE
The relative module was not found

### ISSUE THREAD

**Issue by lopermo** [nuxt-community/storybook#45]
### Version
@nuxtjs/storybook: 1.1.0
nuxt: 2.14

### Steps to reproduce
npx nuxt storybook

### What is Expected?
Work properly with Bootstrap scss files.

### What is actually happening?
The build process crashes with the following message:
```
ERROR  Failed to compile with 1 errors                                                                               
This relative module was not found:                                                                                   
* ./assets/scss/global.scss in ./.nuxt-storybook/storybook/preview.js 
```

My nuxt.config.js is like this:
```
storybook: {
    // Options
    webpackFinal (config, { configType }) {
      // manipulate webpack config
      config.module.rules.push({
        test: /\.scss$/,
        use: ['style-loader', 'css-loader', 'sass-loader'],
        include: resolve(__dirname, '../')
      }, {
        test: /\.s?css$/,
        loader: 'style-loader!css-loader?modules&camelCase&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss-loader!sass-loader'
      })
      return config
    }
  }
```

**EDIT: I just realized that inside preview.js in (.nuxt-storybook/storybook), there is this line, that obviously isn't working:**
``import './assets/scss/global.scss'``
**EDIT 2:** Apparently, that line is being generated from this other one in ``nuxt.config.js``
![dQ54zSndTnupZTzeWgx16s5sgBs9QbtzpVHF2kbv](https://user-images.githubusercontent.com/11388254/89394763-c3a26280-d70c-11ea-94ad-dce2a780bf8f.jpg)
which causes the following error (and I can't make anything of it):
<img width="1279" alt="CleanShot 2020-08-05 at 11 14 42@2x" src="https://user-images.githubusercontent.com/11388254/89394913-ef254d00-d70c-11ea-8c03-29f5506b6bc9.png">

**Comment by farnabaz** [comment]
Could you provide a reproduction sample on codesandbox?

**Comment by danielroe** [comment]
I'm getting a lot of these errors too in a monorepo. Sample:
```bash
ERROR in ./src/plugins/sampleplugin.ts
Module not found: Error: Can't resolve '~/modules/modulefile' in '/mysourcedir/packages/subpackage/src/plugins'
 @ ./src/plugins/sampleplugin.ts 4:0-62 24:19-29 32:19-29 35:40-44
 @ ./.nuxt-storybook/storybook/preview.js
 @ multi /mysourcedir/node_modules/@storybook/core/dist/server/common/polyfills.js /mysourcedir/node_modules/@storybook/core/dist/server/preview/globals.js ./.nuxt-storybook/storybook/preview.js ./.nuxt-storybook/storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=true
```

**Comment by lopermo** [comment]
> Could you provide a reproduction sample on codesandbox?

I can't because I'm working on a commercial product and I can't fork the project there.
I basically I'm trying to get started with Storybook on a project using Bootstrap. A guide for that in the doc would be awesome. I tried the custom installation, but apparently I receive an error about not having 'pages' (I saw another issue here for that)

**Comment by ponnex** [comment]
Mine is working with `import '@/assets/styles/main.scss';` in `preview.js` though I've setup mine through [manual setup](https://storybook.nuxtjs.org/manual-setup)

And I've found out that adding `'style-loader', 'css-loader', 'sass-loader'` in the webpackFinal will cause the same issue so I've used `style-resource-loader` only which works with variables and mixins also

```
config.module.rules.push({
  test: /\.scss$/,
    include: path.resolve(__dirname, '../'),
      use: [{
        loader: 'style-resources-loader',
         options: {
           patterns: globalCSS
         }
     }]
});
```

note have to `npm i style-resource-loader`

**Comment by farnabaz** [comment]
This should fix in the latest version. In the latest releases, CSS imports are extracted from the preview file and Nuxt core handles styles imports.  

I close this issue but feel free to reopen or ask any question

**Comment by lopermo** [comment]
> This should fix in the latest version. In the latest releases, CSS imports are extracted from the preview file and Nuxt core handles styles imports.
> 
> I close this issue but feel free to reopen or ask any question

Sorry to reopen this, but some guide to add UI modules, like Bootstrap would be extremely helpful. I'm trying for many hours to use Storybook with Vue-Bootstrap and I still can't figure out how to do it...
