### ISSUE TITLE
Add abstracted nuxt components

### ISSUE THREAD

**Issue by pimlie** [nuxt-community/storybook#5]
Mostly `nuxt-link` should be abstracted as it shouldnt perform any navigation. 

I've copied this from some nuxt-storybook config I found, but cant remember which one anymore so I cant give proper credits unfortunately. Instead of navigating it logs an action

```js
Vue.component('nuxt-link', {
  props: {
    to: {
      type: String,
      required: true
    }
  },
  methods: {
    log() {
      action('link target')(this.to)
    }
  },
  template: '<a href="#" @click.prevent="log()"><slot>NuxtLink</slot></a>'
})
```

**Comment by farnabaz** [comment]
We have a `mock` directory inside `storybook` that can contain any necessary components

**Comment by drewbaker** [comment]
@farnabaz Is this only in "manual" mode? I'd love to see this documented somewhere? Are components auto loaded out of this mock directory?
