### ISSUE TITLE
Cannot set property 'STORYBOOK_REACT_CLASSES' of undefined

### ISSUE THREAD

**Issue by mkalayci35** [nuxt-community/storybook#51]
### Version
@nuxtjs/storybook: v1.1.0 
nuxt: v2.14.1 

yarn run dev mode: 'universal' problem... 

<img width="1380" alt="Screen Shot 2020-08-05 at 22 10 46" src="https://user-images.githubusercontent.com/38668796/89453859-8370cd80-d768-11ea-94b3-e02c94de207a.png">

**Comment by farnabaz** [comment]
Could you provide a reproduction sample on codesandbox?

**Comment by mkalayci35** [comment]
Sorry I can't. The project is very big. :(

**Comment by mkalayci35** [comment]
> Could you provide a reproduction sample on codesandbox?

Sorry I can't. The project is very big. :(

**Comment by mkalayci35** [comment]
i am .stories.js in document add import Vue from 'vue' and delete import Vue from 'vue'  fixed

**Comment by jblossomweb** [comment]
@productfrontenddeveloper what does your above comment mean? I don't understand. thank you

**Comment by productfrontenddeveloper** [comment]
@jblossomweb 

```import Vue from 'vue' ``` add no add should be as follows.

example used AppButton.stories.js 
```

import AppButton from '@/components/Shared/AppButton.vue'

export default {
	title: 'Component/AppButton',
	component: AppButton,
}
export const allButton = () => ({
	components: { AppButton },
	template: '<span class="h-20"><AppButton primary xs>Merhaba</AppButton></span>',
})

```
