### ISSUE TITLE
Serving a static image

### ISSUE THREAD

**Issue by CodyBontecou** [nuxt-community/storybook#52]
I'm trying to get this basic component to render within the storybook and am having no luck. The component works just fine within my site, but it's not transferring over to Storybook as I'd expect.

`<img src="/logo.png" class="Logo" alt="Logo">`

Are there additional steps needs to run components that utilize static files?

**Comment by farnabaz** [comment]
Hi,
Static files will be supported in [v1.2.0](https://github.com/nuxt-community/storybook/pull/43), It will be out tomorrow.
I close this issue, feel free to reopen it anytime

**Comment by CodyBontecou** [comment]
Good to know, I look forward to it.
