### ISSUE TITLE
Path resolution problem when trying to use @storybook/addon-storyshots

### ISSUE THREAD

**Issue by stephiescastle** [nuxt-community/storybook#53]
Hello, thank you for this excellent module! I'm trying to use [storyshots](https://github.com/storybookjs/storybook/tree/master/addons/storyshots/storyshots-core), and I'm getting a path resolution error. I should also note I'm currently using a release candidate for Storybook 6
```
"@nuxtjs/storybook": "^1.1.0",
"@storybook/addon-storyshots": "^6.0.0-rc.27",
```

And here is my `storyshots.test.js`:

```js
import path from 'path'
import initStoryshots from '@storybook/addon-storyshots'

initStoryshots({
  configPath: path.resolve(__dirname, '../.nuxt-storybook/storybook'),
})

```

It's _almost_ working, but when I set my storyshots `configPath` to use the `.nuxt-storybook` config, it runs into path resolution errors.

```sh
 FAIL  test/storyshots.test.js
  ● Test suite failed to run

    Cannot find module '~~/.nuxt-storybook/utils' from '.nuxt-storybook/storybook/preview.js'

    Require stack:
      .nuxt-storybook/storybook/preview.js
      node_modules/@storybook/addon-storyshots/dist/frameworks/configure.ts
      node_modules/@storybook/addon-storyshots/dist/frameworks/angular/loader.js
      node_modules/@storybook/addon-storyshots/dist/frameworks/frameworkLoader.ts
      node_modules/@storybook/addon-storyshots/dist/api/index.js
      node_modules/@storybook/addon-storyshots/dist/index.js
      test/storyshots.test.js
```

Any tips on what I should set my config path to?

**Comment by stephiescastle** [comment]
Oh, I spoke way too soon 😅 My entire storybook is also broken now, probably because I was trying to use the release candidate. I'll wait until this module officially supports Storybook 6 (which I see will be soon!) and try again.

**Comment by jaskiratr** [comment]
@stephiescastle Did you find a way to implement storyshots with Nuxt?

**Comment by jojoyuji** [comment]
I'm having the same issue, cannot implement storyshots using this module :/

**Comment by jojoyuji** [comment]
Hey @jaskiratr, 

I got it working now! Looking up when you eject this module there's this 
```
import '~~/.nuxt-storybook/storybook/preview.js'
``` 
https://storybook.nuxtjs.org/manual-setup#create-previewjs

So I ended up adding this path to `jest.config.js`: 
```
module.exports = {
  moduleNameMapper: {
    '^~storybook': '<rootDir>/.nuxt-storybook/storybook/preview.js',
    ...
  }
}
```
and this is my `storyshots.test.js`: 
```
import path from 'path'
import initStoryshots from '@storybook/addon-storyshots'

initStoryshots( { configPath: path.resolve(__dirname, './.nuxt-storybook/storybook'), })
```

Its working like a charm now!  🎊

**Comment by jaskiratr** [comment]
Thanks @jojoyuji 

I didn't end up using `preview.js`. I was still getting errors. 
I'm new to Storybook, so not sure exactly what the issue could be.

However, the following configuration worked for me. 

[root]/test/unit/**storybook.spec.js**
```js
import path from 'path'
import initStoryshots from '@storybook/addon-storyshots'
...
initStoryshots({ configPath: path.resolve(__dirname, '../../storybook') })
```

[root]/**jest.config.js**
```js
module.exports = {
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/$1',
    '^~/(.*)$': '<rootDir>/$1',
    '^vue$': 'vue/dist/vue.common.js',
    '^~storybook': '<rootDir>/.nuxt-storybook/storybook/preview.js'
  },
  moduleFileExtensions: ['js', 'vue', 'json'],
  transform: {
    '^.+\\.js$': 'babel-jest',
    '.*\\.(vue)$': 'vue-jest'
    // '.*\\.(vue)$': '<rootDir>/node_modules/jest-vue-preprocessor',
  },
  collectCoverage: false,
  collectCoverageFrom: ['<rootDir>/components/**/*.vue', '<rootDir>/pages/**/*.vue'],
  transformIgnorePatterns: ['/node_modules/(?!(@storybook/.*\\.vue$))'],
  modulePathIgnorePatterns: ['<rootDir>/jsdocs/']
}
```

[root]/storybook/**main.js**
```js
module.exports = {
  webpackFinal(config, options) {
    config = options.nuxtStorybookConfig.webpackFinal(config, options)
    return config
  },
  stories: ['../components/**/*.stories.@(ts|js)'],
  addons: [
    // '@storybook/addon-actions',
    // '@storybook/addon-actions/register',
    '@storybook/addon-knobs',
    '@storybook/addon-links'
  ]
}
```

**Comment by jojoyuji** [comment]
@jaskiratr cool! 

In the end I had to eject nuxt-storybook anyways. I was having a hard time trying to integrate more specific addons 🤷‍♂️

**Comment by dankellett** [comment]
I'm running into a dependency resolution issue for plugins within the nuxt-storybook generated index.js. Did you all run into an error with imports with something like the following?

Cannot find module 'nuxt_plugin_plugin_17783870' from '.nux

import nuxt_plugin_plugin_17783870 from 'nuxt_plugin_plugin_17783870'

**Comment by simondib** [comment]
> @jaskiratr cool!
> 
> In the end I had to eject nuxt-storybook anyways. I was having a hard time trying to integrate more specific addons 🤷‍♂️

@jojoyuji Do you happen to have a repo I can take a look at, or could share some of your babel/jest/storybook configs?
