### ISSUE TITLE
Not possible to reference custom config file

### ISSUE THREAD

**Issue by samturrell** [nuxt-community/storybook#55]
### Is your feature request related to a problem? Please describe.
I'm using nuxt inside of adonis, where the nuxt config is located at `config/nuxt.js`. This module doesn't appear to allow for you to configure where it reads the config from.

### Describe the solution you'd like
A CLI flag to pass in the config file, akin to the nuxt docs (https://nuxtjs.org/guide/commands/) `--config-file` command.

This would allow you to run the following command to start storybook:

```
npx nuxt storybook --config-file config/nuxt.js
```

### Describe alternatives you've considered
N/A

### Additional context
N/A

**Comment by farnabaz** [comment]
Thank you for the issue,
I put this in v1.2.0 milestone.
