### ISSUE TITLE
Addons configuration and decorators

### ISSUE THREAD

**Issue by m-adilshaikh** [nuxt-community/storybook#62]
I am just getting started with storybook, so please bear with me.

I first added  `storybook-addon-paddings`, then jumped into preview.js template to find that plugins are only being imported, wheres plenty of these use addDecorator or things of that sort.

I though I'd try something official, installing `@storybook/addon-console` and adding to nuxt config gave me following.

```
Accessing non-existent addons channel, see https://storybook.js.org/basics/faq/#why-is-there-no-addons-channel
```

Am I missing something or something is not supported? Perhaps we need some addition to the docs?

**Comment by farnabaz** [comment]
It seems that `@storybook/addon-console` addon is not actively maintaining and it has some issues with storybook v5.3.
Take a look at https://github.com/storybookjs/storybook-addon-console/issues/27  
Also if you want to modify `preview.js` and add custom code to this file, you should use [manual setup](https://storybook.nuxtjs.org/manual-setup/). See [manual setup example](https://github.com/nuxt-community/storybook/tree/master/examples/manual-setup)
