### ISSUE TITLE
Bootstrap of `./.nuxt-storybook/storybook/preview.js` does not support asynchonous Nuxt.js plugins

### ISSUE THREAD

**Issue by lihbr** [nuxt-community/storybook#64]
### Version
@nuxtjs/storybook: 1.2.0
nuxt: 2.14.1

### Reproduction Link
https://codesandbox.io/s/musing-sun-7lco1?file=/components/Dummy.vue

### Steps to reproduce

1. Create a Nuxt.js project
2. Add `@nuxtjs/storybook` and `@nuxtjs/prismic` (contains an asynchronous plugin)
3. Create a component and its story using a method provided by the Prismic module (on the sandbox: `asText`)
4. Run Storybook
5. Story fails because `Cannot read property '<method>' of undefined`

### What is Expected?

`@nuxtjs/storybook` should handle asynchronous plugins too when resolving plugins.

### What is actually happening?

`@nuxtjs/storybook` doesn't handle asynchronous plugins when resolving plugins. This happens because methods provided by `@nuxtjs/prismic` are injected through an [`async` Nuxt.js plugin](https://github.com/nuxt-community/prismic-module/blob/master/src/templates/plugins/prismic.js), here this module is just used as an example.

I tried few things but so far I have no idea how to fix that one 🤔

**Comment by bbusch19** [comment]
I am seeing this issue as well. Same modules.

**Comment by farnabaz** [comment]
This should fix in [v2.1.0](https://github.com/nuxt-community/storybook/pull/77)

**Comment by lihbr** [comment]
Yup, tried the 2.1.0-rc.2, works perfectly! This module is truly awesome~
