### ISSUE TITLE
Receiving error when using --static-dir

### ISSUE THREAD

**Issue by gaabrielcs** [nuxt-community/storybook#65]
### Version
@nuxtjs/storybook: 1.2.0
nuxt: 2.14.0

### Steps to reproduce
nuxt storybook --static-dir ./src/static

### What is Expected?
Run the server serving the static files from the dir specified by the command.

### What is actually happening?
![Captura de Tela 2020-08-07 às 16 06 14](https://user-images.githubusercontent.com/50870887/89679998-84b90c00-d8c8-11ea-83f4-434a4545b6e4.png)

And I would recommend too to take a look at the staticDir code because, it is using `staticDir: [path.resolve(options.rootDir, nuxt.options.dir.static)],`, options.rootDir in most cases will be good but for those using the srcDir in the nuxt.config to change only the src directory files, like me in my project, it won't load the default nuxt static folder.

**Comment by farnabaz** [comment]
Thanks for report
This fix will publish in v2
