### ISSUE TITLE
2.0.0 Cannot use the decorators and decorators-legacy plugin together

### ISSUE THREAD

**Issue by mkalayci35** [nuxt-community/storybook#72]
ERROR in ./.nuxt-storybook/storybook/generated-refs.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot use the decorators and decorators-legacy plugin together

nuxt: 2.14.1
stoybook : 2.1.0

**Comment by farnabaz** [comment]
Could you provide a sample reproduction project?

**Comment by mkalayci35** [comment]
Unfortunately.
and 
<img width="921" alt="Screen Shot 2020-08-11 at 13 02 29" src="https://user-images.githubusercontent.com/38668796/89884935-ecc26780-dbd2-11ea-933f-20fb8c2b4326.png">

**Comment by mkalayci35** [comment]
Looks like the decorators and decorators-legacy plugin is loaded at the same time, which should not be done.

**Comment by mkalayci35** [comment]
error continues the same.
<img width="868" alt="Screen Shot 2020-08-14 at 16 39 11" src="https://user-images.githubusercontent.com/38668796/90255239-af690e80-de4c-11ea-8c98-0a472c226f76.png">

**Comment by mkalayci35** [comment]
babel-plugin-transform-decorators delete and install [babel-plugin-proposal-decorators](https://babeljs.io/docs/en/babel-plugin-proposal-decorators) problem fix

**Comment by yogevitz** [comment]
@mkalayci35 can you please elaborate on how you fixed this issue?

**Comment by mkalayci35** [comment]
> @mkalayci35 can you please elaborate on how you fixed this issue?

I wrote above

**Comment by yogevitz** [comment]
@mkalayci35 I'm sorry, I didn't understand from what you wrote.
If you can please explain, thank you :)

**Comment by Noliebe** [comment]
look this,pleas
https://github.com/babel/babel/issues/8012
