### ISSUE TITLE
v2.0 not finding my stories with glob warning

### ISSUE THREAD

**Issue by stephiescastle** [nuxt-community/storybook#75]
### Version
@nuxtjs/storybook: 2.0.0
nuxt: 2.14.0

### Reproduction Link
https://codesandbox.io/s/inspiring-wright-zkznq?file=/components/Link/Link.stories.js

### Steps to reproduce
Run storybook with `npx nuxt storybook`
You will see a warning message "We found no files matching any of the following globs" 

### What is Expected?
For storybook to run and to automatically find my story in `/components/Link/Link.stories.js`

### What is actually happening?
I get a warning message about the glob and how no stories are found. Storybook also doesn't fully load, it hangs when viewing at localhost:3003, perhaps because it can't find any stories?

```
WARN We found no files matching any of the following globs:
WARN 
WARN ~/components/**/*.stories.@(ts|js)
WARN 
WARN Maybe your glob was invalid?
WARN see: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#correct-globs-in-mainjs
```

Note that this works as expected in @nuxtjs/storybook v1.2

**Comment by mkalayci35** [comment]
+1

**Comment by nonlinearcom** [comment]
+1 I'm still seeing this error on @nuxtjs/storybook 2.1

**Comment by dpschen** [comment]
+1 i'm still seeing this error on the current @nuxtjs/storybook 3.2.0

**Comment by farnabaz** [comment]
@dpschen Does it occurs without defining any `stories`?  
Could you create a reproduction sample?
