### ISSUE TITLE
Add (quick) support for enabling specific addons

### ISSUE THREAD

**Issue by pimlie** [nuxt-community/storybook#86]
This issue could be the follow up of #84 

I think adding builtin support for the following addons makes sense because they require additional webpack loaders:
- `@storybook/addon-storysource`
  - [needs `@storybook/source-loader`](https://github.com/storybookjs/storybook/tree/next/addons/storysource) to be able to show the source of your stories file
  - needs a option rule which matches the story files
- `@storybook/addon-docs`
  - also needs `@storybook/source-loader` for showing the individual story source
  - [needs `vue-docgen-loader`](https://github.com/pocka/vue-docgen-loader#getting-started) to be able to automatically show props (and code comments) in the docs args table
    - note: This doesnt seem to be explicitly mentioned in the addon-docs documention for Vue, but for me the loaders arent automatically added. Probably because we are using a fully custom webpack config
  - this addon also needs a `vueDocgenOptions` option that lists all webpack aliases (& maybe module paths)

Also, please note that `@storybook/addon-knobs` will be deprecated with v7 in favor of `@storybook/addon-controls`. Currently some examples are still using `knobs` which might give the wrong impression to users of this module.

**Comment by farnabaz** [comment]
Sorry for the late response @pimlie 
First of all, thank you for your great advices on this module.  

The module perfectly supports additional webpack configs, take a look at [wepback config](https://github.com/nuxt-community/storybook/blob/master/src/webpack.ts). There isn't any need to configure loaders manually they will automatically load on the build time. I've tested both of them in the developing process of our webpack preset. You can approve it by looking at [MDX example](https://github.com/nuxt-community/storybook/tree/master/examples/mdx), `@storybook/addon-docs` is used in this example.  

> Also, please note that @storybook/addon-knobs will be deprecated with v7 in favor of @storybook/addon-controls. Currently some examples are still using knobs which might give the wrong impression to users of this module.  

I didn't know that `knobs`with deprecate in v7. I will change examples to use controls. Thank you ❤️
