### ISSUE TITLE
Runtime Config not working

### ISSUE THREAD

**Issue by adamskeeled** [nuxt-community/storybook#87]
### Version
@nuxtjs/storybook: v2.1.0
nuxt: v2.14.1

### Steps to reproduce
* Add a `publicRuntimeConfig` to `nuxt.config.js`
* Try to access it inside one of the components

### What is Expected?
To return the value that was set in `nuxt.config.js`

### What is actually happening?
It returns `undefined`

**Comment by farnabaz** [comment]
Thanks for the issue :)
This will publish in `v2.2.0`
