### ISSUE TITLE
Vuetify preset module not applying custom variables

### ISSUE THREAD

**Issue by adamskeeled** [nuxt-community/storybook#88]
### Version
@nuxtjs/storybook: v2.1.0
nuxt: v2.14.1

### Steps to reproduce
* Install the `@nuxt/vuetify` module and `vue-cli-plugin-vuetify-preset-rally`
* Add the following to `nuxt.config.js`
```
vuetify: {
    customVariables: ["vue-cli-plugin-vuetify-preset-rally/preset/variables.scss"],
    preset: "vue-cli-plugin-vuetify-preset-rally/preset"
},
build: {
    transpile: ["vue-cli-plugin-vuetify-preset-rally"],
    ...
}
```

### What is Expected?
That whatever is defined in the presets `variables.scss` file to be applied to the components (in other words, for it to prepend that file to all scss files). When running in the normal nuxt environment it works, but not in storybook.

### What is actually happening?
None of those styles are applied

**Comment by farnabaz** [comment]
Wrap your stories inside `v-app`.

Unfortunately, Vuetify forces to use [v-app](https://vuetifyjs.com/en/components/application/) around the application.

**Comment by adamskeeled** [comment]
I actually already had a global decorator which added `v-app` (the example is still a great addition and reference point, thank you!). Unfortunately it still doesn't seem to be applying any of the custom variables defined in a vuetify presets `variables.scss` 😕

**Comment by farnabaz** [comment]
Try adding `v-app` inside the story itself.  
Also, could you provide a reproduction sample? Using `v-app` was solve the issue in my project.

**Comment by adamskeeled** [comment]
Hey @farnabaz, sorry for the late response. With the new 2.2.0 version this seems to working now for me. Regarding adding `v-app` inside the story, I made a comment here https://github.com/nuxt-community/storybook/issues/1#issuecomment-685710468 about that

**Comment by farnabaz** [comment]
Glad to hear it 👍 

I close this issue.
Feel free to reopen it if the issue presists
