### ISSUE TITLE
Storybook Theming

### ISSUE THREAD

**Issue by ponnex** [nuxt-community/storybook#89]
### Is your feature request related to a problem? Please describe.
[Theming storybook](https://storybook.js.org/docs/react/configure/theming)

### Describe the solution you'd like
Add `manager.js` for theming

### Describe alternatives you've considered
N/A

### Additional context
N/A

**Comment by farnabaz** [comment]
You should eject storybook config using [manual setup](https://storybook.nuxtjs.org/manual-setup/)

**Comment by ponnex** [comment]
Resolved by doing the [manual setup](https://storybook.nuxtjs.org/manual-setup/) and adding `manager.js` in folder `storybook` have to fix and setup webpack to resolve some issues though. Below is a sample theming inside `manager.js`

```
import { addons } from '@storybook/addons';
import { create } from '@storybook/theming';
import Logo from '../static/icon.png'

const themeConfig = create({
	base: 'dark',
	brandTitle: 'Hard Hat Asia',
	brandImage: Logo,
	appBg: '#242424',
	appContentBg: '#333333',
	textColor: '#ffcf00',
	barSelectedColor: '#ffcf00',
});

addons.setConfig({
	theme: themeConfig,
});
```

**Comment by ponnex** [comment]
Though would be glad to be able to add theming options in `nuxt.config.js`

```
storybook: {
  theme: {
    // themeConfig here
  }
}
```

**Comment by jojoyuji** [comment]
> Though would be glad to be able to add theming options in `nuxt.config.js`
> 
> ```
> storybook: {
>   theme: {
>     // themeConfig here
>   }
> }
> ```

I also would love this option without having to eject/manual setup

**Comment by Jeromche** [comment]
Dark mode is also possible with the [storybook-dark-mode](https://github.com/hipstersmoothie/storybook-dark-mode) package.

After installing you can add it to `nuxt.config.js` like so:

```
storybook: {
  addons: [
    'storybook-dark-mode/register'
  ],
}
```
